/*
Selling Partner API for Direct Fulfillment Orders

The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vendordirectfulfillmentordersv1

import (
	"encoding/json"
	"fmt"

	"github.com/brendan-hurley/spapi-go/flexbool"
)

// checks if the ShipmentDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShipmentDetails{}

// ShipmentDetails Shipment details required for the shipment.
type ShipmentDetails struct {
	// When true, this is a priority shipment.
	IsPriorityShipment flexbool.FlexBool `json:"isPriorityShipment"`
	// When true, this order is part of a scheduled delivery program.
	IsScheduledDeliveryShipment *flexbool.FlexBool `json:"isScheduledDeliveryShipment,omitempty"`
	// When true, a packing slip is required to be sent to the customer.
	IsPslipRequired flexbool.FlexBool `json:"isPslipRequired"`
	// When true, the order contain a gift. Include the gift message and gift wrap information.
	IsGift *flexbool.FlexBool `json:"isGift,omitempty"`
	// Ship method to be used for shipping the order. Amazon defines ship method codes indicating the shipping carrier and shipment service level. To see the full list of ship methods in use, including both the code and the friendly name, search the 'Help' section on Vendor Central for 'ship methods'.
	ShipMethod string `json:"shipMethod"`
	ShipmentDates ShipmentDates `json:"shipmentDates"`
	// Message to customer for order status.
	MessageToCustomer string `json:"messageToCustomer"`
	AdditionalProperties map[string]interface{}
}

type _ShipmentDetails ShipmentDetails

// NewShipmentDetails instantiates a new ShipmentDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipmentDetails(isPriorityShipment bool, isPslipRequired bool, shipMethod string, shipmentDates ShipmentDates, messageToCustomer string) *ShipmentDetails {
	this := ShipmentDetails{}
	this.IsPriorityShipment = flexbool.FlexBool(isPriorityShipment)
	this.IsPslipRequired = flexbool.FlexBool(isPslipRequired)
	this.ShipMethod = shipMethod
	this.ShipmentDates = shipmentDates
	this.MessageToCustomer = messageToCustomer
	return &this
}

// NewShipmentDetailsWithDefaults instantiates a new ShipmentDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipmentDetailsWithDefaults() *ShipmentDetails {
	this := ShipmentDetails{}
	return &this
}

// GetIsPriorityShipment returns the IsPriorityShipment field value
func (o *ShipmentDetails) GetIsPriorityShipment() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return bool(o.IsPriorityShipment)
}

// GetIsPriorityShipmentOk returns a tuple with the IsPriorityShipment field value
// and a boolean to check if the value has been set.
func (o *ShipmentDetails) GetIsPriorityShipmentOk() (*flexbool.FlexBool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPriorityShipment, true
}

// SetIsPriorityShipment sets field value
func (o *ShipmentDetails) SetIsPriorityShipment(v bool) {
	o.IsPriorityShipment = flexbool.FlexBool(v)
}

// GetIsScheduledDeliveryShipment returns the IsScheduledDeliveryShipment field value if set, zero value otherwise.
func (o *ShipmentDetails) GetIsScheduledDeliveryShipment() bool {
	if o == nil || IsNil(o.IsScheduledDeliveryShipment) {
		var ret bool
		return ret
	}
	return bool(*o.IsScheduledDeliveryShipment)
}

// GetIsScheduledDeliveryShipmentOk returns a tuple with the IsScheduledDeliveryShipment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentDetails) GetIsScheduledDeliveryShipmentOk() (*flexbool.FlexBool, bool) {
	if o == nil || IsNil(o.IsScheduledDeliveryShipment) {
		return nil, false
	}
	return o.IsScheduledDeliveryShipment, true
}

// HasIsScheduledDeliveryShipment returns a boolean if a field has been set.
func (o *ShipmentDetails) HasIsScheduledDeliveryShipment() bool {
	if o != nil && !IsNil(o.IsScheduledDeliveryShipment) {
		return true
	}

	return false
}

// SetIsScheduledDeliveryShipment gets a reference to the given bool and assigns it to the IsScheduledDeliveryShipment field.
func (o *ShipmentDetails) SetIsScheduledDeliveryShipment(v bool) {
	o.IsScheduledDeliveryShipment = flexbool.PtrFlexBool(v)
}

// GetIsPslipRequired returns the IsPslipRequired field value
func (o *ShipmentDetails) GetIsPslipRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return bool(o.IsPslipRequired)
}

// GetIsPslipRequiredOk returns a tuple with the IsPslipRequired field value
// and a boolean to check if the value has been set.
func (o *ShipmentDetails) GetIsPslipRequiredOk() (*flexbool.FlexBool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPslipRequired, true
}

// SetIsPslipRequired sets field value
func (o *ShipmentDetails) SetIsPslipRequired(v bool) {
	o.IsPslipRequired = flexbool.FlexBool(v)
}

// GetIsGift returns the IsGift field value if set, zero value otherwise.
func (o *ShipmentDetails) GetIsGift() bool {
	if o == nil || IsNil(o.IsGift) {
		var ret bool
		return ret
	}
	return bool(*o.IsGift)
}

// GetIsGiftOk returns a tuple with the IsGift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentDetails) GetIsGiftOk() (*flexbool.FlexBool, bool) {
	if o == nil || IsNil(o.IsGift) {
		return nil, false
	}
	return o.IsGift, true
}

// HasIsGift returns a boolean if a field has been set.
func (o *ShipmentDetails) HasIsGift() bool {
	if o != nil && !IsNil(o.IsGift) {
		return true
	}

	return false
}

// SetIsGift gets a reference to the given bool and assigns it to the IsGift field.
func (o *ShipmentDetails) SetIsGift(v bool) {
	o.IsGift = flexbool.PtrFlexBool(v)
}

// GetShipMethod returns the ShipMethod field value
func (o *ShipmentDetails) GetShipMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShipMethod
}

// GetShipMethodOk returns a tuple with the ShipMethod field value
// and a boolean to check if the value has been set.
func (o *ShipmentDetails) GetShipMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipMethod, true
}

// SetShipMethod sets field value
func (o *ShipmentDetails) SetShipMethod(v string) {
	o.ShipMethod = v
}

// GetShipmentDates returns the ShipmentDates field value
func (o *ShipmentDetails) GetShipmentDates() ShipmentDates {
	if o == nil {
		var ret ShipmentDates
		return ret
	}

	return o.ShipmentDates
}

// GetShipmentDatesOk returns a tuple with the ShipmentDates field value
// and a boolean to check if the value has been set.
func (o *ShipmentDetails) GetShipmentDatesOk() (*ShipmentDates, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipmentDates, true
}

// SetShipmentDates sets field value
func (o *ShipmentDetails) SetShipmentDates(v ShipmentDates) {
	o.ShipmentDates = v
}

// GetMessageToCustomer returns the MessageToCustomer field value
func (o *ShipmentDetails) GetMessageToCustomer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageToCustomer
}

// GetMessageToCustomerOk returns a tuple with the MessageToCustomer field value
// and a boolean to check if the value has been set.
func (o *ShipmentDetails) GetMessageToCustomerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageToCustomer, true
}

// SetMessageToCustomer sets field value
func (o *ShipmentDetails) SetMessageToCustomer(v string) {
	o.MessageToCustomer = v
}

func (o ShipmentDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShipmentDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isPriorityShipment"] = o.IsPriorityShipment
	if !IsNil(o.IsScheduledDeliveryShipment) {
		toSerialize["isScheduledDeliveryShipment"] = o.IsScheduledDeliveryShipment
	}
	toSerialize["isPslipRequired"] = o.IsPslipRequired
	if !IsNil(o.IsGift) {
		toSerialize["isGift"] = o.IsGift
	}
	toSerialize["shipMethod"] = o.ShipMethod
	toSerialize["shipmentDates"] = o.ShipmentDates
	toSerialize["messageToCustomer"] = o.MessageToCustomer

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ShipmentDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isPriorityShipment",
		"isPslipRequired",
		"shipMethod",
		"shipmentDates",
		"messageToCustomer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShipmentDetails := _ShipmentDetails{}

	err = json.Unmarshal(data, &varShipmentDetails)

	if err != nil {
		return err
	}

	*o = ShipmentDetails(varShipmentDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "isPriorityShipment")
		delete(additionalProperties, "isScheduledDeliveryShipment")
		delete(additionalProperties, "isPslipRequired")
		delete(additionalProperties, "isGift")
		delete(additionalProperties, "shipMethod")
		delete(additionalProperties, "shipmentDates")
		delete(additionalProperties, "messageToCustomer")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableShipmentDetails struct {
	value *ShipmentDetails
	isSet bool
}

func (v NullableShipmentDetails) Get() *ShipmentDetails {
	return v.value
}

func (v *NullableShipmentDetails) Set(val *ShipmentDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentDetails(val *ShipmentDetails) *NullableShipmentDetails {
	return &NullableShipmentDetails{value: val, isSet: true}
}

func (v NullableShipmentDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


