/*
Selling Partner API for Catalog Items

Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).

API version: 2022-04-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package catalogitems20220401

import (
	"encoding/json"
	"fmt"
)

// checks if the ItemDimensionsByMarketplace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemDimensionsByMarketplace{}

// ItemDimensionsByMarketplace Dimensions that are associated with the item in the Amazon catalog for the indicated `marketplaceId`.
type ItemDimensionsByMarketplace struct {
	// Amazon marketplace identifier. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
	MarketplaceId string `json:"marketplaceId"`
	Item *Dimensions `json:"item,omitempty"`
	Package *Dimensions `json:"package,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ItemDimensionsByMarketplace ItemDimensionsByMarketplace

// NewItemDimensionsByMarketplace instantiates a new ItemDimensionsByMarketplace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemDimensionsByMarketplace(marketplaceId string) *ItemDimensionsByMarketplace {
	this := ItemDimensionsByMarketplace{}
	this.MarketplaceId = marketplaceId
	return &this
}

// NewItemDimensionsByMarketplaceWithDefaults instantiates a new ItemDimensionsByMarketplace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemDimensionsByMarketplaceWithDefaults() *ItemDimensionsByMarketplace {
	this := ItemDimensionsByMarketplace{}
	return &this
}

// GetMarketplaceId returns the MarketplaceId field value
func (o *ItemDimensionsByMarketplace) GetMarketplaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarketplaceId
}

// GetMarketplaceIdOk returns a tuple with the MarketplaceId field value
// and a boolean to check if the value has been set.
func (o *ItemDimensionsByMarketplace) GetMarketplaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarketplaceId, true
}

// SetMarketplaceId sets field value
func (o *ItemDimensionsByMarketplace) SetMarketplaceId(v string) {
	o.MarketplaceId = v
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *ItemDimensionsByMarketplace) GetItem() Dimensions {
	if o == nil || IsNil(o.Item) {
		var ret Dimensions
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemDimensionsByMarketplace) GetItemOk() (*Dimensions, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *ItemDimensionsByMarketplace) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given Dimensions and assigns it to the Item field.
func (o *ItemDimensionsByMarketplace) SetItem(v Dimensions) {
	o.Item = &v
}

// GetPackage returns the Package field value if set, zero value otherwise.
func (o *ItemDimensionsByMarketplace) GetPackage() Dimensions {
	if o == nil || IsNil(o.Package) {
		var ret Dimensions
		return ret
	}
	return *o.Package
}

// GetPackageOk returns a tuple with the Package field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemDimensionsByMarketplace) GetPackageOk() (*Dimensions, bool) {
	if o == nil || IsNil(o.Package) {
		return nil, false
	}
	return o.Package, true
}

// HasPackage returns a boolean if a field has been set.
func (o *ItemDimensionsByMarketplace) HasPackage() bool {
	if o != nil && !IsNil(o.Package) {
		return true
	}

	return false
}

// SetPackage gets a reference to the given Dimensions and assigns it to the Package field.
func (o *ItemDimensionsByMarketplace) SetPackage(v Dimensions) {
	o.Package = &v
}

func (o ItemDimensionsByMarketplace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemDimensionsByMarketplace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["marketplaceId"] = o.MarketplaceId
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	if !IsNil(o.Package) {
		toSerialize["package"] = o.Package
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ItemDimensionsByMarketplace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"marketplaceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varItemDimensionsByMarketplace := _ItemDimensionsByMarketplace{}

	err = json.Unmarshal(data, &varItemDimensionsByMarketplace)

	if err != nil {
		return err
	}

	*o = ItemDimensionsByMarketplace(varItemDimensionsByMarketplace)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "marketplaceId")
		delete(additionalProperties, "item")
		delete(additionalProperties, "package")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableItemDimensionsByMarketplace struct {
	value *ItemDimensionsByMarketplace
	isSet bool
}

func (v NullableItemDimensionsByMarketplace) Get() *ItemDimensionsByMarketplace {
	return v.value
}

func (v *NullableItemDimensionsByMarketplace) Set(val *ItemDimensionsByMarketplace) {
	v.value = val
	v.isSet = true
}

func (v NullableItemDimensionsByMarketplace) IsSet() bool {
	return v.isSet
}

func (v *NullableItemDimensionsByMarketplace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemDimensionsByMarketplace(val *ItemDimensionsByMarketplace) *NullableItemDimensionsByMarketplace {
	return &NullableItemDimensionsByMarketplace{value: val, isSet: true}
}

func (v NullableItemDimensionsByMarketplace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemDimensionsByMarketplace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


