/*
Selling Partner API for Retail Procurement Shipments

The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vendorshipments

import (
	"encoding/json"
	"fmt"
)

// checks if the ContainerItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerItem{}

// ContainerItem Carton/Pallet level details for the item.
type ContainerItem struct {
	// The reference number for the item. Please provide the itemSequenceNumber from the 'items' segment to refer to that item's details here.
	ItemReference string `json:"itemReference"`
	ShippedQuantity ItemQuantity `json:"shippedQuantity"`
	ItemDetails *ItemDetails `json:"itemDetails,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ContainerItem ContainerItem

// NewContainerItem instantiates a new ContainerItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerItem(itemReference string, shippedQuantity ItemQuantity) *ContainerItem {
	this := ContainerItem{}
	this.ItemReference = itemReference
	this.ShippedQuantity = shippedQuantity
	return &this
}

// NewContainerItemWithDefaults instantiates a new ContainerItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerItemWithDefaults() *ContainerItem {
	this := ContainerItem{}
	return &this
}

// GetItemReference returns the ItemReference field value
func (o *ContainerItem) GetItemReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemReference
}

// GetItemReferenceOk returns a tuple with the ItemReference field value
// and a boolean to check if the value has been set.
func (o *ContainerItem) GetItemReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemReference, true
}

// SetItemReference sets field value
func (o *ContainerItem) SetItemReference(v string) {
	o.ItemReference = v
}

// GetShippedQuantity returns the ShippedQuantity field value
func (o *ContainerItem) GetShippedQuantity() ItemQuantity {
	if o == nil {
		var ret ItemQuantity
		return ret
	}

	return o.ShippedQuantity
}

// GetShippedQuantityOk returns a tuple with the ShippedQuantity field value
// and a boolean to check if the value has been set.
func (o *ContainerItem) GetShippedQuantityOk() (*ItemQuantity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShippedQuantity, true
}

// SetShippedQuantity sets field value
func (o *ContainerItem) SetShippedQuantity(v ItemQuantity) {
	o.ShippedQuantity = v
}

// GetItemDetails returns the ItemDetails field value if set, zero value otherwise.
func (o *ContainerItem) GetItemDetails() ItemDetails {
	if o == nil || IsNil(o.ItemDetails) {
		var ret ItemDetails
		return ret
	}
	return *o.ItemDetails
}

// GetItemDetailsOk returns a tuple with the ItemDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerItem) GetItemDetailsOk() (*ItemDetails, bool) {
	if o == nil || IsNil(o.ItemDetails) {
		return nil, false
	}
	return o.ItemDetails, true
}

// HasItemDetails returns a boolean if a field has been set.
func (o *ContainerItem) HasItemDetails() bool {
	if o != nil && !IsNil(o.ItemDetails) {
		return true
	}

	return false
}

// SetItemDetails gets a reference to the given ItemDetails and assigns it to the ItemDetails field.
func (o *ContainerItem) SetItemDetails(v ItemDetails) {
	o.ItemDetails = &v
}

func (o ContainerItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["itemReference"] = o.ItemReference
	toSerialize["shippedQuantity"] = o.ShippedQuantity
	if !IsNil(o.ItemDetails) {
		toSerialize["itemDetails"] = o.ItemDetails
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContainerItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"itemReference",
		"shippedQuantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerItem := _ContainerItem{}

	err = json.Unmarshal(data, &varContainerItem)

	if err != nil {
		return err
	}

	*o = ContainerItem(varContainerItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "itemReference")
		delete(additionalProperties, "shippedQuantity")
		delete(additionalProperties, "itemDetails")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContainerItem struct {
	value *ContainerItem
	isSet bool
}

func (v NullableContainerItem) Get() *ContainerItem {
	return v.value
}

func (v *NullableContainerItem) Set(val *ContainerItem) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerItem) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerItem(val *ContainerItem) *NullableContainerItem {
	return &NullableContainerItem{value: val, isSet: true}
}

func (v NullableContainerItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


