/*
The Selling Partner API for Amazon External Fulfillment Shipments Processing

You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

API version: 2024-09-11
Contact: marketplaceapitest@amazon.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package externalfulfillmentshipments20240911

import (
	"encoding/json"
)

// checks if the InvoiceRequirement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceRequirement{}

// InvoiceRequirement Whether the invoice document is required to be attached to the shipment and its corresponding status.
type InvoiceRequirement struct {
	// Whether the invoice document is required to be attached to the shipment.
	Requirement *string `json:"requirement,omitempty"`
	// The status of the of the invoice document that is attached to the shipment.
	Status *string `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InvoiceRequirement InvoiceRequirement

// NewInvoiceRequirement instantiates a new InvoiceRequirement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceRequirement() *InvoiceRequirement {
	this := InvoiceRequirement{}
	return &this
}

// NewInvoiceRequirementWithDefaults instantiates a new InvoiceRequirement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceRequirementWithDefaults() *InvoiceRequirement {
	this := InvoiceRequirement{}
	return &this
}

// GetRequirement returns the Requirement field value if set, zero value otherwise.
func (o *InvoiceRequirement) GetRequirement() string {
	if o == nil || IsNil(o.Requirement) {
		var ret string
		return ret
	}
	return *o.Requirement
}

// GetRequirementOk returns a tuple with the Requirement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceRequirement) GetRequirementOk() (*string, bool) {
	if o == nil || IsNil(o.Requirement) {
		return nil, false
	}
	return o.Requirement, true
}

// HasRequirement returns a boolean if a field has been set.
func (o *InvoiceRequirement) HasRequirement() bool {
	if o != nil && !IsNil(o.Requirement) {
		return true
	}

	return false
}

// SetRequirement gets a reference to the given string and assigns it to the Requirement field.
func (o *InvoiceRequirement) SetRequirement(v string) {
	o.Requirement = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InvoiceRequirement) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceRequirement) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InvoiceRequirement) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *InvoiceRequirement) SetStatus(v string) {
	o.Status = &v
}

func (o InvoiceRequirement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceRequirement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requirement) {
		toSerialize["requirement"] = o.Requirement
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InvoiceRequirement) UnmarshalJSON(data []byte) (err error) {
	varInvoiceRequirement := _InvoiceRequirement{}

	err = json.Unmarshal(data, &varInvoiceRequirement)

	if err != nil {
		return err
	}

	*o = InvoiceRequirement(varInvoiceRequirement)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requirement")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInvoiceRequirement struct {
	value *InvoiceRequirement
	isSet bool
}

func (v NullableInvoiceRequirement) Get() *InvoiceRequirement {
	return v.value
}

func (v *NullableInvoiceRequirement) Set(val *InvoiceRequirement) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceRequirement) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceRequirement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceRequirement(val *InvoiceRequirement) *NullableInvoiceRequirement {
	return &NullableInvoiceRequirement{value: val, isSet: true}
}

func (v NullableInvoiceRequirement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceRequirement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


