/*
The Selling Partner API for Amazon External Fulfillment Shipments Processing

You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.

API version: 2024-09-11
Contact: marketplaceapitest@amazon.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package externalfulfillmentshipments20240911

import (
	"encoding/json"
)

// checks if the ShipmentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShipmentsResponse{}

// ShipmentsResponse The response of the `getShipments` operation.
type ShipmentsResponse struct {
	// A list of shipments.
	Shipments []Shipment `json:"shipments,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ShipmentsResponse ShipmentsResponse

// NewShipmentsResponse instantiates a new ShipmentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipmentsResponse() *ShipmentsResponse {
	this := ShipmentsResponse{}
	return &this
}

// NewShipmentsResponseWithDefaults instantiates a new ShipmentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipmentsResponseWithDefaults() *ShipmentsResponse {
	this := ShipmentsResponse{}
	return &this
}

// GetShipments returns the Shipments field value if set, zero value otherwise.
func (o *ShipmentsResponse) GetShipments() []Shipment {
	if o == nil || IsNil(o.Shipments) {
		var ret []Shipment
		return ret
	}
	return o.Shipments
}

// GetShipmentsOk returns a tuple with the Shipments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentsResponse) GetShipmentsOk() ([]Shipment, bool) {
	if o == nil || IsNil(o.Shipments) {
		return nil, false
	}
	return o.Shipments, true
}

// HasShipments returns a boolean if a field has been set.
func (o *ShipmentsResponse) HasShipments() bool {
	if o != nil && !IsNil(o.Shipments) {
		return true
	}

	return false
}

// SetShipments gets a reference to the given []Shipment and assigns it to the Shipments field.
func (o *ShipmentsResponse) SetShipments(v []Shipment) {
	o.Shipments = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ShipmentsResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentsResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ShipmentsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *ShipmentsResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o ShipmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShipmentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Shipments) {
		toSerialize["shipments"] = o.Shipments
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ShipmentsResponse) UnmarshalJSON(data []byte) (err error) {
	varShipmentsResponse := _ShipmentsResponse{}

	err = json.Unmarshal(data, &varShipmentsResponse)

	if err != nil {
		return err
	}

	*o = ShipmentsResponse(varShipmentsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "shipments")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableShipmentsResponse struct {
	value *ShipmentsResponse
	isSet bool
}

func (v NullableShipmentsResponse) Get() *ShipmentsResponse {
	return v.value
}

func (v *NullableShipmentsResponse) Set(val *ShipmentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentsResponse(val *ShipmentsResponse) *NullableShipmentsResponse {
	return &NullableShipmentsResponse{value: val, isSet: true}
}

func (v NullableShipmentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


