/*
Selling Partner API for Merchant Fulfillment

With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merchantfulfillmentv0

import (
	"encoding/json"
)

// checks if the LabelCustomization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelCustomization{}

// LabelCustomization Custom text for shipping labels.
type LabelCustomization struct {
	// Custom text to print on the label. Note: Custom text is only included on labels that are in ZPL format (ZPL203). FedEx does not support `CustomTextForLabel`.
	CustomTextForLabel *string `json:"CustomTextForLabel,omitempty"`
	StandardIdForLabel *StandardIdForLabel `json:"StandardIdForLabel,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LabelCustomization LabelCustomization

// NewLabelCustomization instantiates a new LabelCustomization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelCustomization() *LabelCustomization {
	this := LabelCustomization{}
	return &this
}

// NewLabelCustomizationWithDefaults instantiates a new LabelCustomization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelCustomizationWithDefaults() *LabelCustomization {
	this := LabelCustomization{}
	return &this
}

// GetCustomTextForLabel returns the CustomTextForLabel field value if set, zero value otherwise.
func (o *LabelCustomization) GetCustomTextForLabel() string {
	if o == nil || IsNil(o.CustomTextForLabel) {
		var ret string
		return ret
	}
	return *o.CustomTextForLabel
}

// GetCustomTextForLabelOk returns a tuple with the CustomTextForLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelCustomization) GetCustomTextForLabelOk() (*string, bool) {
	if o == nil || IsNil(o.CustomTextForLabel) {
		return nil, false
	}
	return o.CustomTextForLabel, true
}

// HasCustomTextForLabel returns a boolean if a field has been set.
func (o *LabelCustomization) HasCustomTextForLabel() bool {
	if o != nil && !IsNil(o.CustomTextForLabel) {
		return true
	}

	return false
}

// SetCustomTextForLabel gets a reference to the given string and assigns it to the CustomTextForLabel field.
func (o *LabelCustomization) SetCustomTextForLabel(v string) {
	o.CustomTextForLabel = &v
}

// GetStandardIdForLabel returns the StandardIdForLabel field value if set, zero value otherwise.
func (o *LabelCustomization) GetStandardIdForLabel() StandardIdForLabel {
	if o == nil || IsNil(o.StandardIdForLabel) {
		var ret StandardIdForLabel
		return ret
	}
	return *o.StandardIdForLabel
}

// GetStandardIdForLabelOk returns a tuple with the StandardIdForLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelCustomization) GetStandardIdForLabelOk() (*StandardIdForLabel, bool) {
	if o == nil || IsNil(o.StandardIdForLabel) {
		return nil, false
	}
	return o.StandardIdForLabel, true
}

// HasStandardIdForLabel returns a boolean if a field has been set.
func (o *LabelCustomization) HasStandardIdForLabel() bool {
	if o != nil && !IsNil(o.StandardIdForLabel) {
		return true
	}

	return false
}

// SetStandardIdForLabel gets a reference to the given StandardIdForLabel and assigns it to the StandardIdForLabel field.
func (o *LabelCustomization) SetStandardIdForLabel(v StandardIdForLabel) {
	o.StandardIdForLabel = &v
}

func (o LabelCustomization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelCustomization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomTextForLabel) {
		toSerialize["CustomTextForLabel"] = o.CustomTextForLabel
	}
	if !IsNil(o.StandardIdForLabel) {
		toSerialize["StandardIdForLabel"] = o.StandardIdForLabel
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LabelCustomization) UnmarshalJSON(data []byte) (err error) {
	varLabelCustomization := _LabelCustomization{}

	err = json.Unmarshal(data, &varLabelCustomization)

	if err != nil {
		return err
	}

	*o = LabelCustomization(varLabelCustomization)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "CustomTextForLabel")
		delete(additionalProperties, "StandardIdForLabel")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLabelCustomization struct {
	value *LabelCustomization
	isSet bool
}

func (v NullableLabelCustomization) Get() *LabelCustomization {
	return v.value
}

func (v *NullableLabelCustomization) Set(val *LabelCustomization) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelCustomization) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelCustomization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelCustomization(val *LabelCustomization) *NullableLabelCustomization {
	return &NullableLabelCustomization{value: val, isSet: true}
}

func (v NullableLabelCustomization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelCustomization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


