/*
Selling Partner API for Replenishment

The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.

API version: 2022-11-07
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package replenishment20221107

import (
	"encoding/json"
)

// checks if the ListOffersResponseOffer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOffersResponseOffer{}

// ListOffersResponseOffer An object which contains details about an offer.
type ListOffersResponseOffer struct {
	// The SKU. This property is only supported for sellers and not for vendors.
	Sku *string `json:"sku,omitempty"`
	// The Amazon Standard Identification Number (ASIN).
	Asin *string `json:"asin,omitempty"`
	// The marketplace identifier. The supported marketplaces for both sellers and vendors are US, CA, ES, UK, FR, IT, IN, DE, and JP. The supported marketplaces for vendors only are BR, AU, MX, AE, and NL. Refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids) to find the identifier for the marketplace.
	MarketplaceId *string `json:"marketplaceId,omitempty"`
	Eligibility *EligibilityStatus `json:"eligibility,omitempty"`
	OfferProgramConfiguration *OfferProgramConfiguration `json:"offerProgramConfiguration,omitempty"`
	ProgramType *ProgramType `json:"programType,omitempty"`
	// A list of vendor codes associated with the offer.
	VendorCodes []string `json:"vendorCodes,omitempty"`
	// The current price of the offer. This is the listed price amount for the item.
	Price *float64 `json:"price,omitempty"`
	// The currency code in ISO 4217 format for the price. For example, `USD` for US dollars.
	PriceCurrencyCode *string `json:"priceCurrencyCode,omitempty"`
	// The available inventory count for the offer.
	Inventory *int64 `json:"inventory,omitempty"`
	// The stock risk level of the offer, indicating the risk of the offer going out of stock.
	StockRisk *string `json:"stockRisk,omitempty"`
	// A list of delivery conditions for the offer, indicating the health of upcoming deliveries. Each condition describes the quantity of upcoming deliveries associated with a particular delivery condition type.
	DeliveriesConditions []DeliveriesCondition `json:"deliveriesConditions,omitempty"`
	// The number of active subscriptions for the offer.
	Subscriptions *int64 `json:"subscriptions,omitempty"`
	// The fulfillment network identifier type for the offer, indicating how the offer is fulfilled.
	FulfillmentNetworkIDType *string `json:"fulfillmentNetworkIDType,omitempty"`
	ForecastDeliveries *ForecastDeliveries `json:"forecastDeliveries,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListOffersResponseOffer ListOffersResponseOffer

// NewListOffersResponseOffer instantiates a new ListOffersResponseOffer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOffersResponseOffer() *ListOffersResponseOffer {
	this := ListOffersResponseOffer{}
	return &this
}

// NewListOffersResponseOfferWithDefaults instantiates a new ListOffersResponseOffer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOffersResponseOfferWithDefaults() *ListOffersResponseOffer {
	this := ListOffersResponseOffer{}
	return &this
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *ListOffersResponseOffer) SetSku(v string) {
	o.Sku = &v
}

// GetAsin returns the Asin field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetAsin() string {
	if o == nil || IsNil(o.Asin) {
		var ret string
		return ret
	}
	return *o.Asin
}

// GetAsinOk returns a tuple with the Asin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetAsinOk() (*string, bool) {
	if o == nil || IsNil(o.Asin) {
		return nil, false
	}
	return o.Asin, true
}

// HasAsin returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasAsin() bool {
	if o != nil && !IsNil(o.Asin) {
		return true
	}

	return false
}

// SetAsin gets a reference to the given string and assigns it to the Asin field.
func (o *ListOffersResponseOffer) SetAsin(v string) {
	o.Asin = &v
}

// GetMarketplaceId returns the MarketplaceId field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetMarketplaceId() string {
	if o == nil || IsNil(o.MarketplaceId) {
		var ret string
		return ret
	}
	return *o.MarketplaceId
}

// GetMarketplaceIdOk returns a tuple with the MarketplaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetMarketplaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.MarketplaceId) {
		return nil, false
	}
	return o.MarketplaceId, true
}

// HasMarketplaceId returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasMarketplaceId() bool {
	if o != nil && !IsNil(o.MarketplaceId) {
		return true
	}

	return false
}

// SetMarketplaceId gets a reference to the given string and assigns it to the MarketplaceId field.
func (o *ListOffersResponseOffer) SetMarketplaceId(v string) {
	o.MarketplaceId = &v
}

// GetEligibility returns the Eligibility field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetEligibility() EligibilityStatus {
	if o == nil || IsNil(o.Eligibility) {
		var ret EligibilityStatus
		return ret
	}
	return *o.Eligibility
}

// GetEligibilityOk returns a tuple with the Eligibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetEligibilityOk() (*EligibilityStatus, bool) {
	if o == nil || IsNil(o.Eligibility) {
		return nil, false
	}
	return o.Eligibility, true
}

// HasEligibility returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasEligibility() bool {
	if o != nil && !IsNil(o.Eligibility) {
		return true
	}

	return false
}

// SetEligibility gets a reference to the given EligibilityStatus and assigns it to the Eligibility field.
func (o *ListOffersResponseOffer) SetEligibility(v EligibilityStatus) {
	o.Eligibility = &v
}

// GetOfferProgramConfiguration returns the OfferProgramConfiguration field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetOfferProgramConfiguration() OfferProgramConfiguration {
	if o == nil || IsNil(o.OfferProgramConfiguration) {
		var ret OfferProgramConfiguration
		return ret
	}
	return *o.OfferProgramConfiguration
}

// GetOfferProgramConfigurationOk returns a tuple with the OfferProgramConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetOfferProgramConfigurationOk() (*OfferProgramConfiguration, bool) {
	if o == nil || IsNil(o.OfferProgramConfiguration) {
		return nil, false
	}
	return o.OfferProgramConfiguration, true
}

// HasOfferProgramConfiguration returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasOfferProgramConfiguration() bool {
	if o != nil && !IsNil(o.OfferProgramConfiguration) {
		return true
	}

	return false
}

// SetOfferProgramConfiguration gets a reference to the given OfferProgramConfiguration and assigns it to the OfferProgramConfiguration field.
func (o *ListOffersResponseOffer) SetOfferProgramConfiguration(v OfferProgramConfiguration) {
	o.OfferProgramConfiguration = &v
}

// GetProgramType returns the ProgramType field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetProgramType() ProgramType {
	if o == nil || IsNil(o.ProgramType) {
		var ret ProgramType
		return ret
	}
	return *o.ProgramType
}

// GetProgramTypeOk returns a tuple with the ProgramType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetProgramTypeOk() (*ProgramType, bool) {
	if o == nil || IsNil(o.ProgramType) {
		return nil, false
	}
	return o.ProgramType, true
}

// HasProgramType returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasProgramType() bool {
	if o != nil && !IsNil(o.ProgramType) {
		return true
	}

	return false
}

// SetProgramType gets a reference to the given ProgramType and assigns it to the ProgramType field.
func (o *ListOffersResponseOffer) SetProgramType(v ProgramType) {
	o.ProgramType = &v
}

// GetVendorCodes returns the VendorCodes field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetVendorCodes() []string {
	if o == nil || IsNil(o.VendorCodes) {
		var ret []string
		return ret
	}
	return o.VendorCodes
}

// GetVendorCodesOk returns a tuple with the VendorCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetVendorCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.VendorCodes) {
		return nil, false
	}
	return o.VendorCodes, true
}

// HasVendorCodes returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasVendorCodes() bool {
	if o != nil && !IsNil(o.VendorCodes) {
		return true
	}

	return false
}

// SetVendorCodes gets a reference to the given []string and assigns it to the VendorCodes field.
func (o *ListOffersResponseOffer) SetVendorCodes(v []string) {
	o.VendorCodes = v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetPrice() float64 {
	if o == nil || IsNil(o.Price) {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *ListOffersResponseOffer) SetPrice(v float64) {
	o.Price = &v
}

// GetPriceCurrencyCode returns the PriceCurrencyCode field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetPriceCurrencyCode() string {
	if o == nil || IsNil(o.PriceCurrencyCode) {
		var ret string
		return ret
	}
	return *o.PriceCurrencyCode
}

// GetPriceCurrencyCodeOk returns a tuple with the PriceCurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetPriceCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PriceCurrencyCode) {
		return nil, false
	}
	return o.PriceCurrencyCode, true
}

// HasPriceCurrencyCode returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasPriceCurrencyCode() bool {
	if o != nil && !IsNil(o.PriceCurrencyCode) {
		return true
	}

	return false
}

// SetPriceCurrencyCode gets a reference to the given string and assigns it to the PriceCurrencyCode field.
func (o *ListOffersResponseOffer) SetPriceCurrencyCode(v string) {
	o.PriceCurrencyCode = &v
}

// GetInventory returns the Inventory field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetInventory() int64 {
	if o == nil || IsNil(o.Inventory) {
		var ret int64
		return ret
	}
	return *o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetInventoryOk() (*int64, bool) {
	if o == nil || IsNil(o.Inventory) {
		return nil, false
	}
	return o.Inventory, true
}

// HasInventory returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasInventory() bool {
	if o != nil && !IsNil(o.Inventory) {
		return true
	}

	return false
}

// SetInventory gets a reference to the given int64 and assigns it to the Inventory field.
func (o *ListOffersResponseOffer) SetInventory(v int64) {
	o.Inventory = &v
}

// GetStockRisk returns the StockRisk field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetStockRisk() string {
	if o == nil || IsNil(o.StockRisk) {
		var ret string
		return ret
	}
	return *o.StockRisk
}

// GetStockRiskOk returns a tuple with the StockRisk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetStockRiskOk() (*string, bool) {
	if o == nil || IsNil(o.StockRisk) {
		return nil, false
	}
	return o.StockRisk, true
}

// HasStockRisk returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasStockRisk() bool {
	if o != nil && !IsNil(o.StockRisk) {
		return true
	}

	return false
}

// SetStockRisk gets a reference to the given string and assigns it to the StockRisk field.
func (o *ListOffersResponseOffer) SetStockRisk(v string) {
	o.StockRisk = &v
}

// GetDeliveriesConditions returns the DeliveriesConditions field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetDeliveriesConditions() []DeliveriesCondition {
	if o == nil || IsNil(o.DeliveriesConditions) {
		var ret []DeliveriesCondition
		return ret
	}
	return o.DeliveriesConditions
}

// GetDeliveriesConditionsOk returns a tuple with the DeliveriesConditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetDeliveriesConditionsOk() ([]DeliveriesCondition, bool) {
	if o == nil || IsNil(o.DeliveriesConditions) {
		return nil, false
	}
	return o.DeliveriesConditions, true
}

// HasDeliveriesConditions returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasDeliveriesConditions() bool {
	if o != nil && !IsNil(o.DeliveriesConditions) {
		return true
	}

	return false
}

// SetDeliveriesConditions gets a reference to the given []DeliveriesCondition and assigns it to the DeliveriesConditions field.
func (o *ListOffersResponseOffer) SetDeliveriesConditions(v []DeliveriesCondition) {
	o.DeliveriesConditions = v
}

// GetSubscriptions returns the Subscriptions field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetSubscriptions() int64 {
	if o == nil || IsNil(o.Subscriptions) {
		var ret int64
		return ret
	}
	return *o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetSubscriptionsOk() (*int64, bool) {
	if o == nil || IsNil(o.Subscriptions) {
		return nil, false
	}
	return o.Subscriptions, true
}

// HasSubscriptions returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasSubscriptions() bool {
	if o != nil && !IsNil(o.Subscriptions) {
		return true
	}

	return false
}

// SetSubscriptions gets a reference to the given int64 and assigns it to the Subscriptions field.
func (o *ListOffersResponseOffer) SetSubscriptions(v int64) {
	o.Subscriptions = &v
}

// GetFulfillmentNetworkIDType returns the FulfillmentNetworkIDType field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetFulfillmentNetworkIDType() string {
	if o == nil || IsNil(o.FulfillmentNetworkIDType) {
		var ret string
		return ret
	}
	return *o.FulfillmentNetworkIDType
}

// GetFulfillmentNetworkIDTypeOk returns a tuple with the FulfillmentNetworkIDType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetFulfillmentNetworkIDTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FulfillmentNetworkIDType) {
		return nil, false
	}
	return o.FulfillmentNetworkIDType, true
}

// HasFulfillmentNetworkIDType returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasFulfillmentNetworkIDType() bool {
	if o != nil && !IsNil(o.FulfillmentNetworkIDType) {
		return true
	}

	return false
}

// SetFulfillmentNetworkIDType gets a reference to the given string and assigns it to the FulfillmentNetworkIDType field.
func (o *ListOffersResponseOffer) SetFulfillmentNetworkIDType(v string) {
	o.FulfillmentNetworkIDType = &v
}

// GetForecastDeliveries returns the ForecastDeliveries field value if set, zero value otherwise.
func (o *ListOffersResponseOffer) GetForecastDeliveries() ForecastDeliveries {
	if o == nil || IsNil(o.ForecastDeliveries) {
		var ret ForecastDeliveries
		return ret
	}
	return *o.ForecastDeliveries
}

// GetForecastDeliveriesOk returns a tuple with the ForecastDeliveries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOffersResponseOffer) GetForecastDeliveriesOk() (*ForecastDeliveries, bool) {
	if o == nil || IsNil(o.ForecastDeliveries) {
		return nil, false
	}
	return o.ForecastDeliveries, true
}

// HasForecastDeliveries returns a boolean if a field has been set.
func (o *ListOffersResponseOffer) HasForecastDeliveries() bool {
	if o != nil && !IsNil(o.ForecastDeliveries) {
		return true
	}

	return false
}

// SetForecastDeliveries gets a reference to the given ForecastDeliveries and assigns it to the ForecastDeliveries field.
func (o *ListOffersResponseOffer) SetForecastDeliveries(v ForecastDeliveries) {
	o.ForecastDeliveries = &v
}

func (o ListOffersResponseOffer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOffersResponseOffer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.Asin) {
		toSerialize["asin"] = o.Asin
	}
	if !IsNil(o.MarketplaceId) {
		toSerialize["marketplaceId"] = o.MarketplaceId
	}
	if !IsNil(o.Eligibility) {
		toSerialize["eligibility"] = o.Eligibility
	}
	if !IsNil(o.OfferProgramConfiguration) {
		toSerialize["offerProgramConfiguration"] = o.OfferProgramConfiguration
	}
	if !IsNil(o.ProgramType) {
		toSerialize["programType"] = o.ProgramType
	}
	if !IsNil(o.VendorCodes) {
		toSerialize["vendorCodes"] = o.VendorCodes
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.PriceCurrencyCode) {
		toSerialize["priceCurrencyCode"] = o.PriceCurrencyCode
	}
	if !IsNil(o.Inventory) {
		toSerialize["inventory"] = o.Inventory
	}
	if !IsNil(o.StockRisk) {
		toSerialize["stockRisk"] = o.StockRisk
	}
	if !IsNil(o.DeliveriesConditions) {
		toSerialize["deliveriesConditions"] = o.DeliveriesConditions
	}
	if !IsNil(o.Subscriptions) {
		toSerialize["subscriptions"] = o.Subscriptions
	}
	if !IsNil(o.FulfillmentNetworkIDType) {
		toSerialize["fulfillmentNetworkIDType"] = o.FulfillmentNetworkIDType
	}
	if !IsNil(o.ForecastDeliveries) {
		toSerialize["forecastDeliveries"] = o.ForecastDeliveries
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListOffersResponseOffer) UnmarshalJSON(data []byte) (err error) {
	varListOffersResponseOffer := _ListOffersResponseOffer{}

	err = json.Unmarshal(data, &varListOffersResponseOffer)

	if err != nil {
		return err
	}

	*o = ListOffersResponseOffer(varListOffersResponseOffer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sku")
		delete(additionalProperties, "asin")
		delete(additionalProperties, "marketplaceId")
		delete(additionalProperties, "eligibility")
		delete(additionalProperties, "offerProgramConfiguration")
		delete(additionalProperties, "programType")
		delete(additionalProperties, "vendorCodes")
		delete(additionalProperties, "price")
		delete(additionalProperties, "priceCurrencyCode")
		delete(additionalProperties, "inventory")
		delete(additionalProperties, "stockRisk")
		delete(additionalProperties, "deliveriesConditions")
		delete(additionalProperties, "subscriptions")
		delete(additionalProperties, "fulfillmentNetworkIDType")
		delete(additionalProperties, "forecastDeliveries")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListOffersResponseOffer struct {
	value *ListOffersResponseOffer
	isSet bool
}

func (v NullableListOffersResponseOffer) Get() *ListOffersResponseOffer {
	return v.value
}

func (v *NullableListOffersResponseOffer) Set(val *ListOffersResponseOffer) {
	v.value = val
	v.isSet = true
}

func (v NullableListOffersResponseOffer) IsSet() bool {
	return v.isSet
}

func (v *NullableListOffersResponseOffer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOffersResponseOffer(val *ListOffersResponseOffer) *NullableListOffersResponseOffer {
	return &NullableListOffersResponseOffer{value: val, isSet: true}
}

func (v NullableListOffersResponseOffer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOffersResponseOffer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


