/*
Selling Partner API for Replenishment

The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.

API version: 2022-11-07
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package replenishment20221107

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSellingPartnerMetricsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSellingPartnerMetricsRequest{}

// GetSellingPartnerMetricsRequest The request body for the `getSellingPartnerMetrics` operation.
type GetSellingPartnerMetricsRequest struct {
	AggregationFrequency *AggregationFrequency `json:"aggregationFrequency,omitempty"`
	TimeInterval TimeInterval `json:"timeInterval"`
	// The list of metrics requested. If no metric value is provided, data for all of the metrics will be returned.
	Metrics []Metric `json:"metrics,omitempty"`
	TimePeriodType TimePeriodType `json:"timePeriodType"`
	// The marketplace identifier. The supported marketplaces for both sellers and vendors are US, CA, ES, UK, FR, IT, IN, DE, and JP. The supported marketplaces for vendors only are BR, AU, MX, AE, and NL. Refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids) to find the identifier for the marketplace.
	MarketplaceId string `json:"marketplaceId"`
	// A list of replenishment program types.
	ProgramTypes []ProgramType `json:"programTypes"`
	AdditionalProperties map[string]interface{}
}

type _GetSellingPartnerMetricsRequest GetSellingPartnerMetricsRequest

// NewGetSellingPartnerMetricsRequest instantiates a new GetSellingPartnerMetricsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSellingPartnerMetricsRequest(timeInterval TimeInterval, timePeriodType TimePeriodType, marketplaceId string, programTypes []ProgramType) *GetSellingPartnerMetricsRequest {
	this := GetSellingPartnerMetricsRequest{}
	this.TimeInterval = timeInterval
	this.TimePeriodType = timePeriodType
	this.MarketplaceId = marketplaceId
	this.ProgramTypes = programTypes
	return &this
}

// NewGetSellingPartnerMetricsRequestWithDefaults instantiates a new GetSellingPartnerMetricsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSellingPartnerMetricsRequestWithDefaults() *GetSellingPartnerMetricsRequest {
	this := GetSellingPartnerMetricsRequest{}
	return &this
}

// GetAggregationFrequency returns the AggregationFrequency field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsRequest) GetAggregationFrequency() AggregationFrequency {
	if o == nil || IsNil(o.AggregationFrequency) {
		var ret AggregationFrequency
		return ret
	}
	return *o.AggregationFrequency
}

// GetAggregationFrequencyOk returns a tuple with the AggregationFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsRequest) GetAggregationFrequencyOk() (*AggregationFrequency, bool) {
	if o == nil || IsNil(o.AggregationFrequency) {
		return nil, false
	}
	return o.AggregationFrequency, true
}

// HasAggregationFrequency returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsRequest) HasAggregationFrequency() bool {
	if o != nil && !IsNil(o.AggregationFrequency) {
		return true
	}

	return false
}

// SetAggregationFrequency gets a reference to the given AggregationFrequency and assigns it to the AggregationFrequency field.
func (o *GetSellingPartnerMetricsRequest) SetAggregationFrequency(v AggregationFrequency) {
	o.AggregationFrequency = &v
}

// GetTimeInterval returns the TimeInterval field value
func (o *GetSellingPartnerMetricsRequest) GetTimeInterval() TimeInterval {
	if o == nil {
		var ret TimeInterval
		return ret
	}

	return o.TimeInterval
}

// GetTimeIntervalOk returns a tuple with the TimeInterval field value
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsRequest) GetTimeIntervalOk() (*TimeInterval, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeInterval, true
}

// SetTimeInterval sets field value
func (o *GetSellingPartnerMetricsRequest) SetTimeInterval(v TimeInterval) {
	o.TimeInterval = v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsRequest) GetMetrics() []Metric {
	if o == nil || IsNil(o.Metrics) {
		var ret []Metric
		return ret
	}
	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsRequest) GetMetricsOk() ([]Metric, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsRequest) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given []Metric and assigns it to the Metrics field.
func (o *GetSellingPartnerMetricsRequest) SetMetrics(v []Metric) {
	o.Metrics = v
}

// GetTimePeriodType returns the TimePeriodType field value
func (o *GetSellingPartnerMetricsRequest) GetTimePeriodType() TimePeriodType {
	if o == nil {
		var ret TimePeriodType
		return ret
	}

	return o.TimePeriodType
}

// GetTimePeriodTypeOk returns a tuple with the TimePeriodType field value
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsRequest) GetTimePeriodTypeOk() (*TimePeriodType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimePeriodType, true
}

// SetTimePeriodType sets field value
func (o *GetSellingPartnerMetricsRequest) SetTimePeriodType(v TimePeriodType) {
	o.TimePeriodType = v
}

// GetMarketplaceId returns the MarketplaceId field value
func (o *GetSellingPartnerMetricsRequest) GetMarketplaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarketplaceId
}

// GetMarketplaceIdOk returns a tuple with the MarketplaceId field value
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsRequest) GetMarketplaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarketplaceId, true
}

// SetMarketplaceId sets field value
func (o *GetSellingPartnerMetricsRequest) SetMarketplaceId(v string) {
	o.MarketplaceId = v
}

// GetProgramTypes returns the ProgramTypes field value
func (o *GetSellingPartnerMetricsRequest) GetProgramTypes() []ProgramType {
	if o == nil {
		var ret []ProgramType
		return ret
	}

	return o.ProgramTypes
}

// GetProgramTypesOk returns a tuple with the ProgramTypes field value
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsRequest) GetProgramTypesOk() ([]ProgramType, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProgramTypes, true
}

// SetProgramTypes sets field value
func (o *GetSellingPartnerMetricsRequest) SetProgramTypes(v []ProgramType) {
	o.ProgramTypes = v
}

func (o GetSellingPartnerMetricsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSellingPartnerMetricsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AggregationFrequency) {
		toSerialize["aggregationFrequency"] = o.AggregationFrequency
	}
	toSerialize["timeInterval"] = o.TimeInterval
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	toSerialize["timePeriodType"] = o.TimePeriodType
	toSerialize["marketplaceId"] = o.MarketplaceId
	toSerialize["programTypes"] = o.ProgramTypes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSellingPartnerMetricsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timeInterval",
		"timePeriodType",
		"marketplaceId",
		"programTypes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSellingPartnerMetricsRequest := _GetSellingPartnerMetricsRequest{}

	err = json.Unmarshal(data, &varGetSellingPartnerMetricsRequest)

	if err != nil {
		return err
	}

	*o = GetSellingPartnerMetricsRequest(varGetSellingPartnerMetricsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "aggregationFrequency")
		delete(additionalProperties, "timeInterval")
		delete(additionalProperties, "metrics")
		delete(additionalProperties, "timePeriodType")
		delete(additionalProperties, "marketplaceId")
		delete(additionalProperties, "programTypes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSellingPartnerMetricsRequest struct {
	value *GetSellingPartnerMetricsRequest
	isSet bool
}

func (v NullableGetSellingPartnerMetricsRequest) Get() *GetSellingPartnerMetricsRequest {
	return v.value
}

func (v *NullableGetSellingPartnerMetricsRequest) Set(val *GetSellingPartnerMetricsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSellingPartnerMetricsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSellingPartnerMetricsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSellingPartnerMetricsRequest(val *GetSellingPartnerMetricsRequest) *NullableGetSellingPartnerMetricsRequest {
	return &NullableGetSellingPartnerMetricsRequest{value: val, isSet: true}
}

func (v NullableGetSellingPartnerMetricsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSellingPartnerMetricsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


