/*
The Selling Partner API for Amazon Warehousing and Distribution

The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 

API version: 2024-05-09
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package awd20240509

import (
	"encoding/json"
	"fmt"
)

// checks if the DistributionPackageQuantity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributionPackageQuantity{}

// DistributionPackageQuantity Represents a distribution package with its respective quantity.
type DistributionPackageQuantity struct {
	// Number of cases or pallets with the same package configuration.
	Count int32 `json:"count"`
	DistributionPackage DistributionPackage `json:"distributionPackage"`
	AdditionalProperties map[string]interface{}
}

type _DistributionPackageQuantity DistributionPackageQuantity

// NewDistributionPackageQuantity instantiates a new DistributionPackageQuantity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributionPackageQuantity(count int32, distributionPackage DistributionPackage) *DistributionPackageQuantity {
	this := DistributionPackageQuantity{}
	this.Count = count
	this.DistributionPackage = distributionPackage
	return &this
}

// NewDistributionPackageQuantityWithDefaults instantiates a new DistributionPackageQuantity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributionPackageQuantityWithDefaults() *DistributionPackageQuantity {
	this := DistributionPackageQuantity{}
	return &this
}

// GetCount returns the Count field value
func (o *DistributionPackageQuantity) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *DistributionPackageQuantity) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *DistributionPackageQuantity) SetCount(v int32) {
	o.Count = v
}

// GetDistributionPackage returns the DistributionPackage field value
func (o *DistributionPackageQuantity) GetDistributionPackage() DistributionPackage {
	if o == nil {
		var ret DistributionPackage
		return ret
	}

	return o.DistributionPackage
}

// GetDistributionPackageOk returns a tuple with the DistributionPackage field value
// and a boolean to check if the value has been set.
func (o *DistributionPackageQuantity) GetDistributionPackageOk() (*DistributionPackage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistributionPackage, true
}

// SetDistributionPackage sets field value
func (o *DistributionPackageQuantity) SetDistributionPackage(v DistributionPackage) {
	o.DistributionPackage = v
}

func (o DistributionPackageQuantity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributionPackageQuantity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["distributionPackage"] = o.DistributionPackage

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DistributionPackageQuantity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"distributionPackage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributionPackageQuantity := _DistributionPackageQuantity{}

	err = json.Unmarshal(data, &varDistributionPackageQuantity)

	if err != nil {
		return err
	}

	*o = DistributionPackageQuantity(varDistributionPackageQuantity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "count")
		delete(additionalProperties, "distributionPackage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDistributionPackageQuantity struct {
	value *DistributionPackageQuantity
	isSet bool
}

func (v NullableDistributionPackageQuantity) Get() *DistributionPackageQuantity {
	return v.value
}

func (v *NullableDistributionPackageQuantity) Set(val *DistributionPackageQuantity) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributionPackageQuantity) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributionPackageQuantity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributionPackageQuantity(val *DistributionPackageQuantity) *NullableDistributionPackageQuantity {
	return &NullableDistributionPackageQuantity{value: val, isSet: true}
}

func (v NullableDistributionPackageQuantity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributionPackageQuantity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


