/*
The Selling Partner API for Amazon Warehousing and Distribution

The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory. 

API version: 2024-05-09
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package awd20240509

import (
	"encoding/json"
	"fmt"
)

// checks if the MeasurementData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeasurementData{}

// MeasurementData Package weight and dimension.
type MeasurementData struct {
	Dimensions *PackageDimensions `json:"dimensions,omitempty"`
	Volume *PackageVolume `json:"volume,omitempty"`
	Weight PackageWeight `json:"weight"`
	AdditionalProperties map[string]interface{}
}

type _MeasurementData MeasurementData

// NewMeasurementData instantiates a new MeasurementData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeasurementData(weight PackageWeight) *MeasurementData {
	this := MeasurementData{}
	this.Weight = weight
	return &this
}

// NewMeasurementDataWithDefaults instantiates a new MeasurementData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeasurementDataWithDefaults() *MeasurementData {
	this := MeasurementData{}
	return &this
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *MeasurementData) GetDimensions() PackageDimensions {
	if o == nil || IsNil(o.Dimensions) {
		var ret PackageDimensions
		return ret
	}
	return *o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasurementData) GetDimensionsOk() (*PackageDimensions, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return nil, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *MeasurementData) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given PackageDimensions and assigns it to the Dimensions field.
func (o *MeasurementData) SetDimensions(v PackageDimensions) {
	o.Dimensions = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *MeasurementData) GetVolume() PackageVolume {
	if o == nil || IsNil(o.Volume) {
		var ret PackageVolume
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeasurementData) GetVolumeOk() (*PackageVolume, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *MeasurementData) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given PackageVolume and assigns it to the Volume field.
func (o *MeasurementData) SetVolume(v PackageVolume) {
	o.Volume = &v
}

// GetWeight returns the Weight field value
func (o *MeasurementData) GetWeight() PackageWeight {
	if o == nil {
		var ret PackageWeight
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *MeasurementData) GetWeightOk() (*PackageWeight, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *MeasurementData) SetWeight(v PackageWeight) {
	o.Weight = v
}

func (o MeasurementData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeasurementData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	toSerialize["weight"] = o.Weight

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MeasurementData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"weight",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeasurementData := _MeasurementData{}

	err = json.Unmarshal(data, &varMeasurementData)

	if err != nil {
		return err
	}

	*o = MeasurementData(varMeasurementData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dimensions")
		delete(additionalProperties, "volume")
		delete(additionalProperties, "weight")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMeasurementData struct {
	value *MeasurementData
	isSet bool
}

func (v NullableMeasurementData) Get() *MeasurementData {
	return v.value
}

func (v *NullableMeasurementData) Set(val *MeasurementData) {
	v.value = val
	v.isSet = true
}

func (v NullableMeasurementData) IsSet() bool {
	return v.isSet
}

func (v *NullableMeasurementData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeasurementData(val *MeasurementData) *NullableMeasurementData {
	return &NullableMeasurementData{value: val, isSet: true}
}

func (v NullableMeasurementData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeasurementData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


