/*
Selling Partner API for Retail Procurement Payments

The Selling Partner API for Retail Procurement Payments provides programmatic access to vendors payments data.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vendorinvoices

import (
	"encoding/json"
	"fmt"
)

// checks if the AdditionalDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdditionalDetails{}

// AdditionalDetails Additional information provided by the selling party for tax-related or any other purpose.
type AdditionalDetails struct {
	// The type of the additional information provided by the selling party.
	Type string `json:"type"`
	// The detail of the additional information provided by the selling party.
	Detail string `json:"detail"`
	// The language code of the additional information detail.
	LanguageCode *string `json:"languageCode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdditionalDetails AdditionalDetails

// NewAdditionalDetails instantiates a new AdditionalDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdditionalDetails(type_ string, detail string) *AdditionalDetails {
	this := AdditionalDetails{}
	this.Type = type_
	this.Detail = detail
	return &this
}

// NewAdditionalDetailsWithDefaults instantiates a new AdditionalDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdditionalDetailsWithDefaults() *AdditionalDetails {
	this := AdditionalDetails{}
	return &this
}

// GetType returns the Type field value
func (o *AdditionalDetails) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AdditionalDetails) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AdditionalDetails) SetType(v string) {
	o.Type = v
}

// GetDetail returns the Detail field value
func (o *AdditionalDetails) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *AdditionalDetails) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *AdditionalDetails) SetDetail(v string) {
	o.Detail = v
}

// GetLanguageCode returns the LanguageCode field value if set, zero value otherwise.
func (o *AdditionalDetails) GetLanguageCode() string {
	if o == nil || IsNil(o.LanguageCode) {
		var ret string
		return ret
	}
	return *o.LanguageCode
}

// GetLanguageCodeOk returns a tuple with the LanguageCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalDetails) GetLanguageCodeOk() (*string, bool) {
	if o == nil || IsNil(o.LanguageCode) {
		return nil, false
	}
	return o.LanguageCode, true
}

// HasLanguageCode returns a boolean if a field has been set.
func (o *AdditionalDetails) HasLanguageCode() bool {
	if o != nil && !IsNil(o.LanguageCode) {
		return true
	}

	return false
}

// SetLanguageCode gets a reference to the given string and assigns it to the LanguageCode field.
func (o *AdditionalDetails) SetLanguageCode(v string) {
	o.LanguageCode = &v
}

func (o AdditionalDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdditionalDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["detail"] = o.Detail
	if !IsNil(o.LanguageCode) {
		toSerialize["languageCode"] = o.LanguageCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdditionalDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdditionalDetails := _AdditionalDetails{}

	err = json.Unmarshal(data, &varAdditionalDetails)

	if err != nil {
		return err
	}

	*o = AdditionalDetails(varAdditionalDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "detail")
		delete(additionalProperties, "languageCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdditionalDetails struct {
	value *AdditionalDetails
	isSet bool
}

func (v NullableAdditionalDetails) Get() *AdditionalDetails {
	return v.value
}

func (v *NullableAdditionalDetails) Set(val *AdditionalDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAdditionalDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAdditionalDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdditionalDetails(val *AdditionalDetails) *NullableAdditionalDetails {
	return &NullableAdditionalDetails{value: val, isSet: true}
}

func (v NullableAdditionalDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdditionalDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


