/*
Selling Partner API for Product Fees

The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productfeesv0

import (
	"encoding/json"
)

// checks if the GetMyFeesEstimateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMyFeesEstimateRequest{}

// GetMyFeesEstimateRequest Request schema.
type GetMyFeesEstimateRequest struct {
	FeesEstimateRequest *FeesEstimateRequest `json:"FeesEstimateRequest,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetMyFeesEstimateRequest GetMyFeesEstimateRequest

// NewGetMyFeesEstimateRequest instantiates a new GetMyFeesEstimateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMyFeesEstimateRequest() *GetMyFeesEstimateRequest {
	this := GetMyFeesEstimateRequest{}
	return &this
}

// NewGetMyFeesEstimateRequestWithDefaults instantiates a new GetMyFeesEstimateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMyFeesEstimateRequestWithDefaults() *GetMyFeesEstimateRequest {
	this := GetMyFeesEstimateRequest{}
	return &this
}

// GetFeesEstimateRequest returns the FeesEstimateRequest field value if set, zero value otherwise.
func (o *GetMyFeesEstimateRequest) GetFeesEstimateRequest() FeesEstimateRequest {
	if o == nil || IsNil(o.FeesEstimateRequest) {
		var ret FeesEstimateRequest
		return ret
	}
	return *o.FeesEstimateRequest
}

// GetFeesEstimateRequestOk returns a tuple with the FeesEstimateRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMyFeesEstimateRequest) GetFeesEstimateRequestOk() (*FeesEstimateRequest, bool) {
	if o == nil || IsNil(o.FeesEstimateRequest) {
		return nil, false
	}
	return o.FeesEstimateRequest, true
}

// HasFeesEstimateRequest returns a boolean if a field has been set.
func (o *GetMyFeesEstimateRequest) HasFeesEstimateRequest() bool {
	if o != nil && !IsNil(o.FeesEstimateRequest) {
		return true
	}

	return false
}

// SetFeesEstimateRequest gets a reference to the given FeesEstimateRequest and assigns it to the FeesEstimateRequest field.
func (o *GetMyFeesEstimateRequest) SetFeesEstimateRequest(v FeesEstimateRequest) {
	o.FeesEstimateRequest = &v
}

func (o GetMyFeesEstimateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMyFeesEstimateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeesEstimateRequest) {
		toSerialize["FeesEstimateRequest"] = o.FeesEstimateRequest
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetMyFeesEstimateRequest) UnmarshalJSON(data []byte) (err error) {
	varGetMyFeesEstimateRequest := _GetMyFeesEstimateRequest{}

	err = json.Unmarshal(data, &varGetMyFeesEstimateRequest)

	if err != nil {
		return err
	}

	*o = GetMyFeesEstimateRequest(varGetMyFeesEstimateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "FeesEstimateRequest")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetMyFeesEstimateRequest struct {
	value *GetMyFeesEstimateRequest
	isSet bool
}

func (v NullableGetMyFeesEstimateRequest) Get() *GetMyFeesEstimateRequest {
	return v.value
}

func (v *NullableGetMyFeesEstimateRequest) Set(val *GetMyFeesEstimateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMyFeesEstimateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMyFeesEstimateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMyFeesEstimateRequest(val *GetMyFeesEstimateRequest) *NullableGetMyFeesEstimateRequest {
	return &NullableGetMyFeesEstimateRequest{value: val, isSet: true}
}

func (v NullableGetMyFeesEstimateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMyFeesEstimateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


