/*
Selling Partner API for Product Fees

The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package productfeesv0

import (
	"encoding/json"
	"fmt"
)

// checks if the GetMyFeesEstimatesErrorList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMyFeesEstimatesErrorList{}

// GetMyFeesEstimatesErrorList A list of error responses returned when a request is unsuccessful.
type GetMyFeesEstimatesErrorList struct {
	// A list of error responses returned when a request is unsuccessful.
	Errors []Error `json:"errors"`
	AdditionalProperties map[string]interface{}
}

type _GetMyFeesEstimatesErrorList GetMyFeesEstimatesErrorList

// NewGetMyFeesEstimatesErrorList instantiates a new GetMyFeesEstimatesErrorList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMyFeesEstimatesErrorList(errors []Error) *GetMyFeesEstimatesErrorList {
	this := GetMyFeesEstimatesErrorList{}
	this.Errors = errors
	return &this
}

// NewGetMyFeesEstimatesErrorListWithDefaults instantiates a new GetMyFeesEstimatesErrorList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMyFeesEstimatesErrorListWithDefaults() *GetMyFeesEstimatesErrorList {
	this := GetMyFeesEstimatesErrorList{}
	return &this
}

// GetErrors returns the Errors field value
func (o *GetMyFeesEstimatesErrorList) GetErrors() []Error {
	if o == nil {
		var ret []Error
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *GetMyFeesEstimatesErrorList) GetErrorsOk() ([]Error, bool) {
	if o == nil {
		return nil, false
	}
	return o.Errors, true
}

// SetErrors sets field value
func (o *GetMyFeesEstimatesErrorList) SetErrors(v []Error) {
	o.Errors = v
}

func (o GetMyFeesEstimatesErrorList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMyFeesEstimatesErrorList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["errors"] = o.Errors

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetMyFeesEstimatesErrorList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"errors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetMyFeesEstimatesErrorList := _GetMyFeesEstimatesErrorList{}

	err = json.Unmarshal(data, &varGetMyFeesEstimatesErrorList)

	if err != nil {
		return err
	}

	*o = GetMyFeesEstimatesErrorList(varGetMyFeesEstimatesErrorList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetMyFeesEstimatesErrorList struct {
	value *GetMyFeesEstimatesErrorList
	isSet bool
}

func (v NullableGetMyFeesEstimatesErrorList) Get() *GetMyFeesEstimatesErrorList {
	return v.value
}

func (v *NullableGetMyFeesEstimatesErrorList) Set(val *GetMyFeesEstimatesErrorList) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMyFeesEstimatesErrorList) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMyFeesEstimatesErrorList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMyFeesEstimatesErrorList(val *GetMyFeesEstimatesErrorList) *NullableGetMyFeesEstimatesErrorList {
	return &NullableGetMyFeesEstimatesErrorList{value: val, isSet: true}
}

func (v NullableGetMyFeesEstimatesErrorList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMyFeesEstimatesErrorList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


