/*
The Selling Partner API for Amazon External Fulfillment Return Item Processing

You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.

API version: 2024-09-11
Contact: marketplaceapitest@amazon.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package externalfulfillmentreturns20240911

import (
	"encoding/json"
)

// checks if the MarketplaceChannelDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketplaceChannelDetails{}

// MarketplaceChannelDetails Marketplace channel-specific attributes for the return. These attributes are not mandatory and each channel can provide them differently.
type MarketplaceChannelDetails struct {
	MarketplaceChannel *MarketplaceChannel `json:"marketplaceChannel,omitempty"`
	// The ID of the merchant or seller to whom this return is created in the marketplace.
	MerchantId *string `json:"merchantId,omitempty"`
	// The marketplace-specific shipment ID.
	ShipmentId *string `json:"shipmentId,omitempty"`
	// The marketplace-specific customer order ID.
	CustomerOrderId *string `json:"customerOrderId,omitempty"`
	// The Amazon SmartConnect ID of the location to which this return is created.
	ReturnLocationId *string `json:"returnLocationId,omitempty"`
	// The Amazon SmartConnect SKU of the channel.
	ChannelSku *string `json:"channelSku,omitempty"`
	// The Amazon SmartConnect ID of the exchange order.
	ExchangeOrderId *string `json:"exchangeOrderId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MarketplaceChannelDetails MarketplaceChannelDetails

// NewMarketplaceChannelDetails instantiates a new MarketplaceChannelDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketplaceChannelDetails() *MarketplaceChannelDetails {
	this := MarketplaceChannelDetails{}
	return &this
}

// NewMarketplaceChannelDetailsWithDefaults instantiates a new MarketplaceChannelDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketplaceChannelDetailsWithDefaults() *MarketplaceChannelDetails {
	this := MarketplaceChannelDetails{}
	return &this
}

// GetMarketplaceChannel returns the MarketplaceChannel field value if set, zero value otherwise.
func (o *MarketplaceChannelDetails) GetMarketplaceChannel() MarketplaceChannel {
	if o == nil || IsNil(o.MarketplaceChannel) {
		var ret MarketplaceChannel
		return ret
	}
	return *o.MarketplaceChannel
}

// GetMarketplaceChannelOk returns a tuple with the MarketplaceChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceChannelDetails) GetMarketplaceChannelOk() (*MarketplaceChannel, bool) {
	if o == nil || IsNil(o.MarketplaceChannel) {
		return nil, false
	}
	return o.MarketplaceChannel, true
}

// HasMarketplaceChannel returns a boolean if a field has been set.
func (o *MarketplaceChannelDetails) HasMarketplaceChannel() bool {
	if o != nil && !IsNil(o.MarketplaceChannel) {
		return true
	}

	return false
}

// SetMarketplaceChannel gets a reference to the given MarketplaceChannel and assigns it to the MarketplaceChannel field.
func (o *MarketplaceChannelDetails) SetMarketplaceChannel(v MarketplaceChannel) {
	o.MarketplaceChannel = &v
}

// GetMerchantId returns the MerchantId field value if set, zero value otherwise.
func (o *MarketplaceChannelDetails) GetMerchantId() string {
	if o == nil || IsNil(o.MerchantId) {
		var ret string
		return ret
	}
	return *o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceChannelDetails) GetMerchantIdOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantId) {
		return nil, false
	}
	return o.MerchantId, true
}

// HasMerchantId returns a boolean if a field has been set.
func (o *MarketplaceChannelDetails) HasMerchantId() bool {
	if o != nil && !IsNil(o.MerchantId) {
		return true
	}

	return false
}

// SetMerchantId gets a reference to the given string and assigns it to the MerchantId field.
func (o *MarketplaceChannelDetails) SetMerchantId(v string) {
	o.MerchantId = &v
}

// GetShipmentId returns the ShipmentId field value if set, zero value otherwise.
func (o *MarketplaceChannelDetails) GetShipmentId() string {
	if o == nil || IsNil(o.ShipmentId) {
		var ret string
		return ret
	}
	return *o.ShipmentId
}

// GetShipmentIdOk returns a tuple with the ShipmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceChannelDetails) GetShipmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShipmentId) {
		return nil, false
	}
	return o.ShipmentId, true
}

// HasShipmentId returns a boolean if a field has been set.
func (o *MarketplaceChannelDetails) HasShipmentId() bool {
	if o != nil && !IsNil(o.ShipmentId) {
		return true
	}

	return false
}

// SetShipmentId gets a reference to the given string and assigns it to the ShipmentId field.
func (o *MarketplaceChannelDetails) SetShipmentId(v string) {
	o.ShipmentId = &v
}

// GetCustomerOrderId returns the CustomerOrderId field value if set, zero value otherwise.
func (o *MarketplaceChannelDetails) GetCustomerOrderId() string {
	if o == nil || IsNil(o.CustomerOrderId) {
		var ret string
		return ret
	}
	return *o.CustomerOrderId
}

// GetCustomerOrderIdOk returns a tuple with the CustomerOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceChannelDetails) GetCustomerOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerOrderId) {
		return nil, false
	}
	return o.CustomerOrderId, true
}

// HasCustomerOrderId returns a boolean if a field has been set.
func (o *MarketplaceChannelDetails) HasCustomerOrderId() bool {
	if o != nil && !IsNil(o.CustomerOrderId) {
		return true
	}

	return false
}

// SetCustomerOrderId gets a reference to the given string and assigns it to the CustomerOrderId field.
func (o *MarketplaceChannelDetails) SetCustomerOrderId(v string) {
	o.CustomerOrderId = &v
}

// GetReturnLocationId returns the ReturnLocationId field value if set, zero value otherwise.
func (o *MarketplaceChannelDetails) GetReturnLocationId() string {
	if o == nil || IsNil(o.ReturnLocationId) {
		var ret string
		return ret
	}
	return *o.ReturnLocationId
}

// GetReturnLocationIdOk returns a tuple with the ReturnLocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceChannelDetails) GetReturnLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnLocationId) {
		return nil, false
	}
	return o.ReturnLocationId, true
}

// HasReturnLocationId returns a boolean if a field has been set.
func (o *MarketplaceChannelDetails) HasReturnLocationId() bool {
	if o != nil && !IsNil(o.ReturnLocationId) {
		return true
	}

	return false
}

// SetReturnLocationId gets a reference to the given string and assigns it to the ReturnLocationId field.
func (o *MarketplaceChannelDetails) SetReturnLocationId(v string) {
	o.ReturnLocationId = &v
}

// GetChannelSku returns the ChannelSku field value if set, zero value otherwise.
func (o *MarketplaceChannelDetails) GetChannelSku() string {
	if o == nil || IsNil(o.ChannelSku) {
		var ret string
		return ret
	}
	return *o.ChannelSku
}

// GetChannelSkuOk returns a tuple with the ChannelSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceChannelDetails) GetChannelSkuOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelSku) {
		return nil, false
	}
	return o.ChannelSku, true
}

// HasChannelSku returns a boolean if a field has been set.
func (o *MarketplaceChannelDetails) HasChannelSku() bool {
	if o != nil && !IsNil(o.ChannelSku) {
		return true
	}

	return false
}

// SetChannelSku gets a reference to the given string and assigns it to the ChannelSku field.
func (o *MarketplaceChannelDetails) SetChannelSku(v string) {
	o.ChannelSku = &v
}

// GetExchangeOrderId returns the ExchangeOrderId field value if set, zero value otherwise.
func (o *MarketplaceChannelDetails) GetExchangeOrderId() string {
	if o == nil || IsNil(o.ExchangeOrderId) {
		var ret string
		return ret
	}
	return *o.ExchangeOrderId
}

// GetExchangeOrderIdOk returns a tuple with the ExchangeOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceChannelDetails) GetExchangeOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExchangeOrderId) {
		return nil, false
	}
	return o.ExchangeOrderId, true
}

// HasExchangeOrderId returns a boolean if a field has been set.
func (o *MarketplaceChannelDetails) HasExchangeOrderId() bool {
	if o != nil && !IsNil(o.ExchangeOrderId) {
		return true
	}

	return false
}

// SetExchangeOrderId gets a reference to the given string and assigns it to the ExchangeOrderId field.
func (o *MarketplaceChannelDetails) SetExchangeOrderId(v string) {
	o.ExchangeOrderId = &v
}

func (o MarketplaceChannelDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketplaceChannelDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MarketplaceChannel) {
		toSerialize["marketplaceChannel"] = o.MarketplaceChannel
	}
	if !IsNil(o.MerchantId) {
		toSerialize["merchantId"] = o.MerchantId
	}
	if !IsNil(o.ShipmentId) {
		toSerialize["shipmentId"] = o.ShipmentId
	}
	if !IsNil(o.CustomerOrderId) {
		toSerialize["customerOrderId"] = o.CustomerOrderId
	}
	if !IsNil(o.ReturnLocationId) {
		toSerialize["returnLocationId"] = o.ReturnLocationId
	}
	if !IsNil(o.ChannelSku) {
		toSerialize["channelSku"] = o.ChannelSku
	}
	if !IsNil(o.ExchangeOrderId) {
		toSerialize["exchangeOrderId"] = o.ExchangeOrderId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MarketplaceChannelDetails) UnmarshalJSON(data []byte) (err error) {
	varMarketplaceChannelDetails := _MarketplaceChannelDetails{}

	err = json.Unmarshal(data, &varMarketplaceChannelDetails)

	if err != nil {
		return err
	}

	*o = MarketplaceChannelDetails(varMarketplaceChannelDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "marketplaceChannel")
		delete(additionalProperties, "merchantId")
		delete(additionalProperties, "shipmentId")
		delete(additionalProperties, "customerOrderId")
		delete(additionalProperties, "returnLocationId")
		delete(additionalProperties, "channelSku")
		delete(additionalProperties, "exchangeOrderId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMarketplaceChannelDetails struct {
	value *MarketplaceChannelDetails
	isSet bool
}

func (v NullableMarketplaceChannelDetails) Get() *MarketplaceChannelDetails {
	return v.value
}

func (v *NullableMarketplaceChannelDetails) Set(val *MarketplaceChannelDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketplaceChannelDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketplaceChannelDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketplaceChannelDetails(val *MarketplaceChannelDetails) *NullableMarketplaceChannelDetails {
	return &NullableMarketplaceChannelDetails{value: val, isSet: true}
}

func (v NullableMarketplaceChannelDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketplaceChannelDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


