/*
The Selling Partner API for Finances

The Selling Partner API for Finances provides financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.

API version: 2024-06-19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finances20240619

import (
	"encoding/json"
)

// checks if the AmazonPayContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AmazonPayContext{}

// AmazonPayContext Additional information related to Amazon Pay.
type AmazonPayContext struct {
	// The name of the store that is related to the transaction.
	StoreName *string `json:"storeName,omitempty"`
	// The transaction's order type.
	OrderType *string `json:"orderType,omitempty"`
	// Channel details of related transaction.
	Channel *string `json:"channel,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AmazonPayContext AmazonPayContext

// NewAmazonPayContext instantiates a new AmazonPayContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmazonPayContext() *AmazonPayContext {
	this := AmazonPayContext{}
	return &this
}

// NewAmazonPayContextWithDefaults instantiates a new AmazonPayContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmazonPayContextWithDefaults() *AmazonPayContext {
	this := AmazonPayContext{}
	return &this
}

// GetStoreName returns the StoreName field value if set, zero value otherwise.
func (o *AmazonPayContext) GetStoreName() string {
	if o == nil || IsNil(o.StoreName) {
		var ret string
		return ret
	}
	return *o.StoreName
}

// GetStoreNameOk returns a tuple with the StoreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonPayContext) GetStoreNameOk() (*string, bool) {
	if o == nil || IsNil(o.StoreName) {
		return nil, false
	}
	return o.StoreName, true
}

// HasStoreName returns a boolean if a field has been set.
func (o *AmazonPayContext) HasStoreName() bool {
	if o != nil && !IsNil(o.StoreName) {
		return true
	}

	return false
}

// SetStoreName gets a reference to the given string and assigns it to the StoreName field.
func (o *AmazonPayContext) SetStoreName(v string) {
	o.StoreName = &v
}

// GetOrderType returns the OrderType field value if set, zero value otherwise.
func (o *AmazonPayContext) GetOrderType() string {
	if o == nil || IsNil(o.OrderType) {
		var ret string
		return ret
	}
	return *o.OrderType
}

// GetOrderTypeOk returns a tuple with the OrderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonPayContext) GetOrderTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OrderType) {
		return nil, false
	}
	return o.OrderType, true
}

// HasOrderType returns a boolean if a field has been set.
func (o *AmazonPayContext) HasOrderType() bool {
	if o != nil && !IsNil(o.OrderType) {
		return true
	}

	return false
}

// SetOrderType gets a reference to the given string and assigns it to the OrderType field.
func (o *AmazonPayContext) SetOrderType(v string) {
	o.OrderType = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *AmazonPayContext) GetChannel() string {
	if o == nil || IsNil(o.Channel) {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AmazonPayContext) GetChannelOk() (*string, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *AmazonPayContext) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *AmazonPayContext) SetChannel(v string) {
	o.Channel = &v
}

func (o AmazonPayContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AmazonPayContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StoreName) {
		toSerialize["storeName"] = o.StoreName
	}
	if !IsNil(o.OrderType) {
		toSerialize["orderType"] = o.OrderType
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AmazonPayContext) UnmarshalJSON(data []byte) (err error) {
	varAmazonPayContext := _AmazonPayContext{}

	err = json.Unmarshal(data, &varAmazonPayContext)

	if err != nil {
		return err
	}

	*o = AmazonPayContext(varAmazonPayContext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "storeName")
		delete(additionalProperties, "orderType")
		delete(additionalProperties, "channel")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAmazonPayContext struct {
	value *AmazonPayContext
	isSet bool
}

func (v NullableAmazonPayContext) Get() *AmazonPayContext {
	return v.value
}

func (v *NullableAmazonPayContext) Set(val *AmazonPayContext) {
	v.value = val
	v.isSet = true
}

func (v NullableAmazonPayContext) IsSet() bool {
	return v.isSet
}

func (v *NullableAmazonPayContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmazonPayContext(val *AmazonPayContext) *NullableAmazonPayContext {
	return &NullableAmazonPayContext{value: val, isSet: true}
}

func (v NullableAmazonPayContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmazonPayContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


