/*
The Selling Partner API for Finances

The Selling Partner API for Finances provides financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.

API version: 2024-06-19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finances20240619

import (
	"encoding/json"
)

// checks if the BusinessContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BusinessContext{}

// BusinessContext Information about the line of business associated with a transaction.
type BusinessContext struct {
	// The store name associated with the transaction.
	StoreName *string `json:"storeName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BusinessContext BusinessContext

// NewBusinessContext instantiates a new BusinessContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBusinessContext() *BusinessContext {
	this := BusinessContext{}
	return &this
}

// NewBusinessContextWithDefaults instantiates a new BusinessContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBusinessContextWithDefaults() *BusinessContext {
	this := BusinessContext{}
	return &this
}

// GetStoreName returns the StoreName field value if set, zero value otherwise.
func (o *BusinessContext) GetStoreName() string {
	if o == nil || IsNil(o.StoreName) {
		var ret string
		return ret
	}
	return *o.StoreName
}

// GetStoreNameOk returns a tuple with the StoreName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessContext) GetStoreNameOk() (*string, bool) {
	if o == nil || IsNil(o.StoreName) {
		return nil, false
	}
	return o.StoreName, true
}

// HasStoreName returns a boolean if a field has been set.
func (o *BusinessContext) HasStoreName() bool {
	if o != nil && !IsNil(o.StoreName) {
		return true
	}

	return false
}

// SetStoreName gets a reference to the given string and assigns it to the StoreName field.
func (o *BusinessContext) SetStoreName(v string) {
	o.StoreName = &v
}

func (o BusinessContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BusinessContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StoreName) {
		toSerialize["storeName"] = o.StoreName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BusinessContext) UnmarshalJSON(data []byte) (err error) {
	varBusinessContext := _BusinessContext{}

	err = json.Unmarshal(data, &varBusinessContext)

	if err != nil {
		return err
	}

	*o = BusinessContext(varBusinessContext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "storeName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBusinessContext struct {
	value *BusinessContext
	isSet bool
}

func (v NullableBusinessContext) Get() *BusinessContext {
	return v.value
}

func (v *NullableBusinessContext) Set(val *BusinessContext) {
	v.value = val
	v.isSet = true
}

func (v NullableBusinessContext) IsSet() bool {
	return v.isSet
}

func (v *NullableBusinessContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBusinessContext(val *BusinessContext) *NullableBusinessContext {
	return &NullableBusinessContext{value: val, isSet: true}
}

func (v NullableBusinessContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBusinessContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


