/*
Selling Partner API for Orders

Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ordersv0

import (
	"encoding/json"
	"fmt"
)

// checks if the RegulatedOrderVerificationStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegulatedOrderVerificationStatus{}

// RegulatedOrderVerificationStatus The verification status of the order, along with associated approval or rejection metadata.
type RegulatedOrderVerificationStatus struct {
	Status VerificationStatus `json:"Status"`
	// When true, the regulated information provided in the order requires a review by the merchant.
	RequiresMerchantAction bool `json:"RequiresMerchantAction"`
	// A list of valid rejection reasons that may be used to reject the order's regulated information.
	ValidRejectionReasons []RejectionReason `json:"ValidRejectionReasons"`
	RejectionReason *RejectionReason `json:"RejectionReason,omitempty"`
	// The date the order was reviewed. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format.
	ReviewDate *string `json:"ReviewDate,omitempty"`
	// The identifier for the order's regulated information reviewer.
	ExternalReviewerId *string `json:"ExternalReviewerId,omitempty"`
	// A list of valid verification details that may be provided and the criteria required for when the verification detail can be provided.
	ValidVerificationDetails []ValidVerificationDetail `json:"ValidVerificationDetails,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RegulatedOrderVerificationStatus RegulatedOrderVerificationStatus

// NewRegulatedOrderVerificationStatus instantiates a new RegulatedOrderVerificationStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegulatedOrderVerificationStatus(status VerificationStatus, requiresMerchantAction bool, validRejectionReasons []RejectionReason) *RegulatedOrderVerificationStatus {
	this := RegulatedOrderVerificationStatus{}
	this.Status = status
	this.RequiresMerchantAction = requiresMerchantAction
	this.ValidRejectionReasons = validRejectionReasons
	return &this
}

// NewRegulatedOrderVerificationStatusWithDefaults instantiates a new RegulatedOrderVerificationStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegulatedOrderVerificationStatusWithDefaults() *RegulatedOrderVerificationStatus {
	this := RegulatedOrderVerificationStatus{}
	return &this
}

// GetStatus returns the Status field value
func (o *RegulatedOrderVerificationStatus) GetStatus() VerificationStatus {
	if o == nil {
		var ret VerificationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RegulatedOrderVerificationStatus) GetStatusOk() (*VerificationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RegulatedOrderVerificationStatus) SetStatus(v VerificationStatus) {
	o.Status = v
}

// GetRequiresMerchantAction returns the RequiresMerchantAction field value
func (o *RegulatedOrderVerificationStatus) GetRequiresMerchantAction() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresMerchantAction
}

// GetRequiresMerchantActionOk returns a tuple with the RequiresMerchantAction field value
// and a boolean to check if the value has been set.
func (o *RegulatedOrderVerificationStatus) GetRequiresMerchantActionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresMerchantAction, true
}

// SetRequiresMerchantAction sets field value
func (o *RegulatedOrderVerificationStatus) SetRequiresMerchantAction(v bool) {
	o.RequiresMerchantAction = v
}

// GetValidRejectionReasons returns the ValidRejectionReasons field value
func (o *RegulatedOrderVerificationStatus) GetValidRejectionReasons() []RejectionReason {
	if o == nil {
		var ret []RejectionReason
		return ret
	}

	return o.ValidRejectionReasons
}

// GetValidRejectionReasonsOk returns a tuple with the ValidRejectionReasons field value
// and a boolean to check if the value has been set.
func (o *RegulatedOrderVerificationStatus) GetValidRejectionReasonsOk() ([]RejectionReason, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValidRejectionReasons, true
}

// SetValidRejectionReasons sets field value
func (o *RegulatedOrderVerificationStatus) SetValidRejectionReasons(v []RejectionReason) {
	o.ValidRejectionReasons = v
}

// GetRejectionReason returns the RejectionReason field value if set, zero value otherwise.
func (o *RegulatedOrderVerificationStatus) GetRejectionReason() RejectionReason {
	if o == nil || IsNil(o.RejectionReason) {
		var ret RejectionReason
		return ret
	}
	return *o.RejectionReason
}

// GetRejectionReasonOk returns a tuple with the RejectionReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegulatedOrderVerificationStatus) GetRejectionReasonOk() (*RejectionReason, bool) {
	if o == nil || IsNil(o.RejectionReason) {
		return nil, false
	}
	return o.RejectionReason, true
}

// HasRejectionReason returns a boolean if a field has been set.
func (o *RegulatedOrderVerificationStatus) HasRejectionReason() bool {
	if o != nil && !IsNil(o.RejectionReason) {
		return true
	}

	return false
}

// SetRejectionReason gets a reference to the given RejectionReason and assigns it to the RejectionReason field.
func (o *RegulatedOrderVerificationStatus) SetRejectionReason(v RejectionReason) {
	o.RejectionReason = &v
}

// GetReviewDate returns the ReviewDate field value if set, zero value otherwise.
func (o *RegulatedOrderVerificationStatus) GetReviewDate() string {
	if o == nil || IsNil(o.ReviewDate) {
		var ret string
		return ret
	}
	return *o.ReviewDate
}

// GetReviewDateOk returns a tuple with the ReviewDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegulatedOrderVerificationStatus) GetReviewDateOk() (*string, bool) {
	if o == nil || IsNil(o.ReviewDate) {
		return nil, false
	}
	return o.ReviewDate, true
}

// HasReviewDate returns a boolean if a field has been set.
func (o *RegulatedOrderVerificationStatus) HasReviewDate() bool {
	if o != nil && !IsNil(o.ReviewDate) {
		return true
	}

	return false
}

// SetReviewDate gets a reference to the given string and assigns it to the ReviewDate field.
func (o *RegulatedOrderVerificationStatus) SetReviewDate(v string) {
	o.ReviewDate = &v
}

// GetExternalReviewerId returns the ExternalReviewerId field value if set, zero value otherwise.
func (o *RegulatedOrderVerificationStatus) GetExternalReviewerId() string {
	if o == nil || IsNil(o.ExternalReviewerId) {
		var ret string
		return ret
	}
	return *o.ExternalReviewerId
}

// GetExternalReviewerIdOk returns a tuple with the ExternalReviewerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegulatedOrderVerificationStatus) GetExternalReviewerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalReviewerId) {
		return nil, false
	}
	return o.ExternalReviewerId, true
}

// HasExternalReviewerId returns a boolean if a field has been set.
func (o *RegulatedOrderVerificationStatus) HasExternalReviewerId() bool {
	if o != nil && !IsNil(o.ExternalReviewerId) {
		return true
	}

	return false
}

// SetExternalReviewerId gets a reference to the given string and assigns it to the ExternalReviewerId field.
func (o *RegulatedOrderVerificationStatus) SetExternalReviewerId(v string) {
	o.ExternalReviewerId = &v
}

// GetValidVerificationDetails returns the ValidVerificationDetails field value if set, zero value otherwise.
func (o *RegulatedOrderVerificationStatus) GetValidVerificationDetails() []ValidVerificationDetail {
	if o == nil || IsNil(o.ValidVerificationDetails) {
		var ret []ValidVerificationDetail
		return ret
	}
	return o.ValidVerificationDetails
}

// GetValidVerificationDetailsOk returns a tuple with the ValidVerificationDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegulatedOrderVerificationStatus) GetValidVerificationDetailsOk() ([]ValidVerificationDetail, bool) {
	if o == nil || IsNil(o.ValidVerificationDetails) {
		return nil, false
	}
	return o.ValidVerificationDetails, true
}

// HasValidVerificationDetails returns a boolean if a field has been set.
func (o *RegulatedOrderVerificationStatus) HasValidVerificationDetails() bool {
	if o != nil && !IsNil(o.ValidVerificationDetails) {
		return true
	}

	return false
}

// SetValidVerificationDetails gets a reference to the given []ValidVerificationDetail and assigns it to the ValidVerificationDetails field.
func (o *RegulatedOrderVerificationStatus) SetValidVerificationDetails(v []ValidVerificationDetail) {
	o.ValidVerificationDetails = v
}

func (o RegulatedOrderVerificationStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegulatedOrderVerificationStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Status"] = o.Status
	toSerialize["RequiresMerchantAction"] = o.RequiresMerchantAction
	toSerialize["ValidRejectionReasons"] = o.ValidRejectionReasons
	if !IsNil(o.RejectionReason) {
		toSerialize["RejectionReason"] = o.RejectionReason
	}
	if !IsNil(o.ReviewDate) {
		toSerialize["ReviewDate"] = o.ReviewDate
	}
	if !IsNil(o.ExternalReviewerId) {
		toSerialize["ExternalReviewerId"] = o.ExternalReviewerId
	}
	if !IsNil(o.ValidVerificationDetails) {
		toSerialize["ValidVerificationDetails"] = o.ValidVerificationDetails
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegulatedOrderVerificationStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Status",
		"RequiresMerchantAction",
		"ValidRejectionReasons",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegulatedOrderVerificationStatus := _RegulatedOrderVerificationStatus{}

	err = json.Unmarshal(data, &varRegulatedOrderVerificationStatus)

	if err != nil {
		return err
	}

	*o = RegulatedOrderVerificationStatus(varRegulatedOrderVerificationStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Status")
		delete(additionalProperties, "RequiresMerchantAction")
		delete(additionalProperties, "ValidRejectionReasons")
		delete(additionalProperties, "RejectionReason")
		delete(additionalProperties, "ReviewDate")
		delete(additionalProperties, "ExternalReviewerId")
		delete(additionalProperties, "ValidVerificationDetails")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegulatedOrderVerificationStatus struct {
	value *RegulatedOrderVerificationStatus
	isSet bool
}

func (v NullableRegulatedOrderVerificationStatus) Get() *RegulatedOrderVerificationStatus {
	return v.value
}

func (v *NullableRegulatedOrderVerificationStatus) Set(val *RegulatedOrderVerificationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRegulatedOrderVerificationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRegulatedOrderVerificationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegulatedOrderVerificationStatus(val *RegulatedOrderVerificationStatus) *NullableRegulatedOrderVerificationStatus {
	return &NullableRegulatedOrderVerificationStatus{value: val, isSet: true}
}

func (v NullableRegulatedOrderVerificationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegulatedOrderVerificationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


