/*
The Selling Partner API for Orders

The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.

API version: 2026-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders20260101

import (
	"encoding/json"
)

// checks if the MerchantAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantAddress{}

// MerchantAddress The physical address of the merchant.
type MerchantAddress struct {
	// The name of the business or facility at this address.
	Name *string `json:"name,omitempty"`
	// The primary street address of the merchant's location.
	AddressLine1 *string `json:"addressLine1,omitempty"`
	// Additional address information.
	AddressLine2 *string `json:"addressLine2,omitempty"`
	// Additional address information.
	AddressLine3 *string `json:"addressLine3,omitempty"`
	// The city of the address.
	City *string `json:"city,omitempty"`
	// The district or county of the address.
	DistrictOrCounty *string `json:"districtOrCounty,omitempty"`
	// The state, province, or region of the address.
	StateOrRegion *string `json:"stateOrRegion,omitempty"`
	// The municipality of the address.
	Municipality *string `json:"municipality,omitempty"`
	// The postal code or ZIP code of the address.
	PostalCode *string `json:"postalCode,omitempty"`
	// The two-letter country code for the address, in ISO 3166-1 format.
	CountryCode *string `json:"countryCode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MerchantAddress MerchantAddress

// NewMerchantAddress instantiates a new MerchantAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantAddress() *MerchantAddress {
	this := MerchantAddress{}
	return &this
}

// NewMerchantAddressWithDefaults instantiates a new MerchantAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantAddressWithDefaults() *MerchantAddress {
	this := MerchantAddress{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MerchantAddress) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MerchantAddress) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MerchantAddress) SetName(v string) {
	o.Name = &v
}

// GetAddressLine1 returns the AddressLine1 field value if set, zero value otherwise.
func (o *MerchantAddress) GetAddressLine1() string {
	if o == nil || IsNil(o.AddressLine1) {
		var ret string
		return ret
	}
	return *o.AddressLine1
}

// GetAddressLine1Ok returns a tuple with the AddressLine1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetAddressLine1Ok() (*string, bool) {
	if o == nil || IsNil(o.AddressLine1) {
		return nil, false
	}
	return o.AddressLine1, true
}

// HasAddressLine1 returns a boolean if a field has been set.
func (o *MerchantAddress) HasAddressLine1() bool {
	if o != nil && !IsNil(o.AddressLine1) {
		return true
	}

	return false
}

// SetAddressLine1 gets a reference to the given string and assigns it to the AddressLine1 field.
func (o *MerchantAddress) SetAddressLine1(v string) {
	o.AddressLine1 = &v
}

// GetAddressLine2 returns the AddressLine2 field value if set, zero value otherwise.
func (o *MerchantAddress) GetAddressLine2() string {
	if o == nil || IsNil(o.AddressLine2) {
		var ret string
		return ret
	}
	return *o.AddressLine2
}

// GetAddressLine2Ok returns a tuple with the AddressLine2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetAddressLine2Ok() (*string, bool) {
	if o == nil || IsNil(o.AddressLine2) {
		return nil, false
	}
	return o.AddressLine2, true
}

// HasAddressLine2 returns a boolean if a field has been set.
func (o *MerchantAddress) HasAddressLine2() bool {
	if o != nil && !IsNil(o.AddressLine2) {
		return true
	}

	return false
}

// SetAddressLine2 gets a reference to the given string and assigns it to the AddressLine2 field.
func (o *MerchantAddress) SetAddressLine2(v string) {
	o.AddressLine2 = &v
}

// GetAddressLine3 returns the AddressLine3 field value if set, zero value otherwise.
func (o *MerchantAddress) GetAddressLine3() string {
	if o == nil || IsNil(o.AddressLine3) {
		var ret string
		return ret
	}
	return *o.AddressLine3
}

// GetAddressLine3Ok returns a tuple with the AddressLine3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetAddressLine3Ok() (*string, bool) {
	if o == nil || IsNil(o.AddressLine3) {
		return nil, false
	}
	return o.AddressLine3, true
}

// HasAddressLine3 returns a boolean if a field has been set.
func (o *MerchantAddress) HasAddressLine3() bool {
	if o != nil && !IsNil(o.AddressLine3) {
		return true
	}

	return false
}

// SetAddressLine3 gets a reference to the given string and assigns it to the AddressLine3 field.
func (o *MerchantAddress) SetAddressLine3(v string) {
	o.AddressLine3 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *MerchantAddress) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *MerchantAddress) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *MerchantAddress) SetCity(v string) {
	o.City = &v
}

// GetDistrictOrCounty returns the DistrictOrCounty field value if set, zero value otherwise.
func (o *MerchantAddress) GetDistrictOrCounty() string {
	if o == nil || IsNil(o.DistrictOrCounty) {
		var ret string
		return ret
	}
	return *o.DistrictOrCounty
}

// GetDistrictOrCountyOk returns a tuple with the DistrictOrCounty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetDistrictOrCountyOk() (*string, bool) {
	if o == nil || IsNil(o.DistrictOrCounty) {
		return nil, false
	}
	return o.DistrictOrCounty, true
}

// HasDistrictOrCounty returns a boolean if a field has been set.
func (o *MerchantAddress) HasDistrictOrCounty() bool {
	if o != nil && !IsNil(o.DistrictOrCounty) {
		return true
	}

	return false
}

// SetDistrictOrCounty gets a reference to the given string and assigns it to the DistrictOrCounty field.
func (o *MerchantAddress) SetDistrictOrCounty(v string) {
	o.DistrictOrCounty = &v
}

// GetStateOrRegion returns the StateOrRegion field value if set, zero value otherwise.
func (o *MerchantAddress) GetStateOrRegion() string {
	if o == nil || IsNil(o.StateOrRegion) {
		var ret string
		return ret
	}
	return *o.StateOrRegion
}

// GetStateOrRegionOk returns a tuple with the StateOrRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetStateOrRegionOk() (*string, bool) {
	if o == nil || IsNil(o.StateOrRegion) {
		return nil, false
	}
	return o.StateOrRegion, true
}

// HasStateOrRegion returns a boolean if a field has been set.
func (o *MerchantAddress) HasStateOrRegion() bool {
	if o != nil && !IsNil(o.StateOrRegion) {
		return true
	}

	return false
}

// SetStateOrRegion gets a reference to the given string and assigns it to the StateOrRegion field.
func (o *MerchantAddress) SetStateOrRegion(v string) {
	o.StateOrRegion = &v
}

// GetMunicipality returns the Municipality field value if set, zero value otherwise.
func (o *MerchantAddress) GetMunicipality() string {
	if o == nil || IsNil(o.Municipality) {
		var ret string
		return ret
	}
	return *o.Municipality
}

// GetMunicipalityOk returns a tuple with the Municipality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetMunicipalityOk() (*string, bool) {
	if o == nil || IsNil(o.Municipality) {
		return nil, false
	}
	return o.Municipality, true
}

// HasMunicipality returns a boolean if a field has been set.
func (o *MerchantAddress) HasMunicipality() bool {
	if o != nil && !IsNil(o.Municipality) {
		return true
	}

	return false
}

// SetMunicipality gets a reference to the given string and assigns it to the Municipality field.
func (o *MerchantAddress) SetMunicipality(v string) {
	o.Municipality = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *MerchantAddress) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *MerchantAddress) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *MerchantAddress) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *MerchantAddress) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantAddress) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *MerchantAddress) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *MerchantAddress) SetCountryCode(v string) {
	o.CountryCode = &v
}

func (o MerchantAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AddressLine1) {
		toSerialize["addressLine1"] = o.AddressLine1
	}
	if !IsNil(o.AddressLine2) {
		toSerialize["addressLine2"] = o.AddressLine2
	}
	if !IsNil(o.AddressLine3) {
		toSerialize["addressLine3"] = o.AddressLine3
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.DistrictOrCounty) {
		toSerialize["districtOrCounty"] = o.DistrictOrCounty
	}
	if !IsNil(o.StateOrRegion) {
		toSerialize["stateOrRegion"] = o.StateOrRegion
	}
	if !IsNil(o.Municipality) {
		toSerialize["municipality"] = o.Municipality
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.CountryCode) {
		toSerialize["countryCode"] = o.CountryCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MerchantAddress) UnmarshalJSON(data []byte) (err error) {
	varMerchantAddress := _MerchantAddress{}

	err = json.Unmarshal(data, &varMerchantAddress)

	if err != nil {
		return err
	}

	*o = MerchantAddress(varMerchantAddress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "addressLine1")
		delete(additionalProperties, "addressLine2")
		delete(additionalProperties, "addressLine3")
		delete(additionalProperties, "city")
		delete(additionalProperties, "districtOrCounty")
		delete(additionalProperties, "stateOrRegion")
		delete(additionalProperties, "municipality")
		delete(additionalProperties, "postalCode")
		delete(additionalProperties, "countryCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMerchantAddress struct {
	value *MerchantAddress
	isSet bool
}

func (v NullableMerchantAddress) Get() *MerchantAddress {
	return v.value
}

func (v *NullableMerchantAddress) Set(val *MerchantAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantAddress(val *MerchantAddress) *NullableMerchantAddress {
	return &NullableMerchantAddress{value: val, isSet: true}
}

func (v NullableMerchantAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


