/*
Selling Partner API for Shipping

Provides programmatic access to Amazon Shipping APIs.   **Note:** If you are new to the Amazon Shipping API, refer to the latest version of <a href=\"https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference\">Amazon Shipping API (v2)</a> on the <a href=\"https://developer-docs.amazon.com/amazon-shipping/\">Amazon Shipping Developer Documentation</a> site.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipping

import (
	"encoding/json"
)

// checks if the GetTrackingInformationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTrackingInformationResponse{}

// GetTrackingInformationResponse The response schema for the getTrackingInformation operation.
type GetTrackingInformationResponse struct {
	Payload *TrackingInformation `json:"payload,omitempty"`
	// A list of error responses returned when a request is unsuccessful.
	Errors []Error `json:"errors,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetTrackingInformationResponse GetTrackingInformationResponse

// NewGetTrackingInformationResponse instantiates a new GetTrackingInformationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTrackingInformationResponse() *GetTrackingInformationResponse {
	this := GetTrackingInformationResponse{}
	return &this
}

// NewGetTrackingInformationResponseWithDefaults instantiates a new GetTrackingInformationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTrackingInformationResponseWithDefaults() *GetTrackingInformationResponse {
	this := GetTrackingInformationResponse{}
	return &this
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *GetTrackingInformationResponse) GetPayload() TrackingInformation {
	if o == nil || IsNil(o.Payload) {
		var ret TrackingInformation
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTrackingInformationResponse) GetPayloadOk() (*TrackingInformation, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *GetTrackingInformationResponse) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given TrackingInformation and assigns it to the Payload field.
func (o *GetTrackingInformationResponse) SetPayload(v TrackingInformation) {
	o.Payload = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *GetTrackingInformationResponse) GetErrors() []Error {
	if o == nil || IsNil(o.Errors) {
		var ret []Error
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTrackingInformationResponse) GetErrorsOk() ([]Error, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *GetTrackingInformationResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error and assigns it to the Errors field.
func (o *GetTrackingInformationResponse) SetErrors(v []Error) {
	o.Errors = v
}

func (o GetTrackingInformationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTrackingInformationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetTrackingInformationResponse) UnmarshalJSON(data []byte) (err error) {
	varGetTrackingInformationResponse := _GetTrackingInformationResponse{}

	err = json.Unmarshal(data, &varGetTrackingInformationResponse)

	if err != nil {
		return err
	}

	*o = GetTrackingInformationResponse(varGetTrackingInformationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "payload")
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetTrackingInformationResponse struct {
	value *GetTrackingInformationResponse
	isSet bool
}

func (v NullableGetTrackingInformationResponse) Get() *GetTrackingInformationResponse {
	return v.value
}

func (v *NullableGetTrackingInformationResponse) Set(val *GetTrackingInformationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTrackingInformationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTrackingInformationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTrackingInformationResponse(val *GetTrackingInformationResponse) *NullableGetTrackingInformationResponse {
	return &NullableGetTrackingInformationResponse{value: val, isSet: true}
}

func (v NullableGetTrackingInformationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTrackingInformationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


