/*
Selling Partner APIs for Fulfillment Outbound

The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

API version: 2020-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillmentoutbound20200701

import (
	"encoding/json"
	"fmt"
)

// checks if the InvalidReturnItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvalidReturnItem{}

// InvalidReturnItem An item that is invalid for return.
type InvalidReturnItem struct {
	// An identifier the seller assigns to the return item.
	SellerReturnItemId string `json:"sellerReturnItemId"`
	// The identifier assigned to the item by the seller when the fulfillment order was created.
	SellerFulfillmentOrderItemId string `json:"sellerFulfillmentOrderItemId"`
	InvalidItemReason InvalidItemReason `json:"invalidItemReason"`
	AdditionalProperties map[string]interface{}
}

type _InvalidReturnItem InvalidReturnItem

// NewInvalidReturnItem instantiates a new InvalidReturnItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvalidReturnItem(sellerReturnItemId string, sellerFulfillmentOrderItemId string, invalidItemReason InvalidItemReason) *InvalidReturnItem {
	this := InvalidReturnItem{}
	this.SellerReturnItemId = sellerReturnItemId
	this.SellerFulfillmentOrderItemId = sellerFulfillmentOrderItemId
	this.InvalidItemReason = invalidItemReason
	return &this
}

// NewInvalidReturnItemWithDefaults instantiates a new InvalidReturnItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvalidReturnItemWithDefaults() *InvalidReturnItem {
	this := InvalidReturnItem{}
	return &this
}

// GetSellerReturnItemId returns the SellerReturnItemId field value
func (o *InvalidReturnItem) GetSellerReturnItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SellerReturnItemId
}

// GetSellerReturnItemIdOk returns a tuple with the SellerReturnItemId field value
// and a boolean to check if the value has been set.
func (o *InvalidReturnItem) GetSellerReturnItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SellerReturnItemId, true
}

// SetSellerReturnItemId sets field value
func (o *InvalidReturnItem) SetSellerReturnItemId(v string) {
	o.SellerReturnItemId = v
}

// GetSellerFulfillmentOrderItemId returns the SellerFulfillmentOrderItemId field value
func (o *InvalidReturnItem) GetSellerFulfillmentOrderItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SellerFulfillmentOrderItemId
}

// GetSellerFulfillmentOrderItemIdOk returns a tuple with the SellerFulfillmentOrderItemId field value
// and a boolean to check if the value has been set.
func (o *InvalidReturnItem) GetSellerFulfillmentOrderItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SellerFulfillmentOrderItemId, true
}

// SetSellerFulfillmentOrderItemId sets field value
func (o *InvalidReturnItem) SetSellerFulfillmentOrderItemId(v string) {
	o.SellerFulfillmentOrderItemId = v
}

// GetInvalidItemReason returns the InvalidItemReason field value
func (o *InvalidReturnItem) GetInvalidItemReason() InvalidItemReason {
	if o == nil {
		var ret InvalidItemReason
		return ret
	}

	return o.InvalidItemReason
}

// GetInvalidItemReasonOk returns a tuple with the InvalidItemReason field value
// and a boolean to check if the value has been set.
func (o *InvalidReturnItem) GetInvalidItemReasonOk() (*InvalidItemReason, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvalidItemReason, true
}

// SetInvalidItemReason sets field value
func (o *InvalidReturnItem) SetInvalidItemReason(v InvalidItemReason) {
	o.InvalidItemReason = v
}

func (o InvalidReturnItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvalidReturnItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sellerReturnItemId"] = o.SellerReturnItemId
	toSerialize["sellerFulfillmentOrderItemId"] = o.SellerFulfillmentOrderItemId
	toSerialize["invalidItemReason"] = o.InvalidItemReason

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InvalidReturnItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sellerReturnItemId",
		"sellerFulfillmentOrderItemId",
		"invalidItemReason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvalidReturnItem := _InvalidReturnItem{}

	err = json.Unmarshal(data, &varInvalidReturnItem)

	if err != nil {
		return err
	}

	*o = InvalidReturnItem(varInvalidReturnItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sellerReturnItemId")
		delete(additionalProperties, "sellerFulfillmentOrderItemId")
		delete(additionalProperties, "invalidItemReason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInvalidReturnItem struct {
	value *InvalidReturnItem
	isSet bool
}

func (v NullableInvalidReturnItem) Get() *InvalidReturnItem {
	return v.value
}

func (v *NullableInvalidReturnItem) Set(val *InvalidReturnItem) {
	v.value = val
	v.isSet = true
}

func (v NullableInvalidReturnItem) IsSet() bool {
	return v.isSet
}

func (v *NullableInvalidReturnItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvalidReturnItem(val *InvalidReturnItem) *NullableInvalidReturnItem {
	return &NullableInvalidReturnItem{value: val, isSet: true}
}

func (v NullableInvalidReturnItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvalidReturnItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


