/*
Selling Partner APIs for Fulfillment Outbound

The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

API version: 2020-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillmentoutbound20200701

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the TrackingEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackingEvent{}

// TrackingEvent Information for tracking package deliveries.
type TrackingEvent struct {
	// Date timestamp
	EventDate time.Time `json:"eventDate"`
	EventAddress TrackingAddress `json:"eventAddress"`
	EventCode EventCode `json:"eventCode"`
	// A description for the corresponding event code.
	EventDescription string `json:"eventDescription"`
	AdditionalProperties map[string]interface{}
}

type _TrackingEvent TrackingEvent

// NewTrackingEvent instantiates a new TrackingEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackingEvent(eventDate time.Time, eventAddress TrackingAddress, eventCode EventCode, eventDescription string) *TrackingEvent {
	this := TrackingEvent{}
	this.EventDate = eventDate
	this.EventAddress = eventAddress
	this.EventCode = eventCode
	this.EventDescription = eventDescription
	return &this
}

// NewTrackingEventWithDefaults instantiates a new TrackingEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackingEventWithDefaults() *TrackingEvent {
	this := TrackingEvent{}
	return &this
}

// GetEventDate returns the EventDate field value
func (o *TrackingEvent) GetEventDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EventDate
}

// GetEventDateOk returns a tuple with the EventDate field value
// and a boolean to check if the value has been set.
func (o *TrackingEvent) GetEventDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventDate, true
}

// SetEventDate sets field value
func (o *TrackingEvent) SetEventDate(v time.Time) {
	o.EventDate = v
}

// GetEventAddress returns the EventAddress field value
func (o *TrackingEvent) GetEventAddress() TrackingAddress {
	if o == nil {
		var ret TrackingAddress
		return ret
	}

	return o.EventAddress
}

// GetEventAddressOk returns a tuple with the EventAddress field value
// and a boolean to check if the value has been set.
func (o *TrackingEvent) GetEventAddressOk() (*TrackingAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventAddress, true
}

// SetEventAddress sets field value
func (o *TrackingEvent) SetEventAddress(v TrackingAddress) {
	o.EventAddress = v
}

// GetEventCode returns the EventCode field value
func (o *TrackingEvent) GetEventCode() EventCode {
	if o == nil {
		var ret EventCode
		return ret
	}

	return o.EventCode
}

// GetEventCodeOk returns a tuple with the EventCode field value
// and a boolean to check if the value has been set.
func (o *TrackingEvent) GetEventCodeOk() (*EventCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventCode, true
}

// SetEventCode sets field value
func (o *TrackingEvent) SetEventCode(v EventCode) {
	o.EventCode = v
}

// GetEventDescription returns the EventDescription field value
func (o *TrackingEvent) GetEventDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventDescription
}

// GetEventDescriptionOk returns a tuple with the EventDescription field value
// and a boolean to check if the value has been set.
func (o *TrackingEvent) GetEventDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventDescription, true
}

// SetEventDescription sets field value
func (o *TrackingEvent) SetEventDescription(v string) {
	o.EventDescription = v
}

func (o TrackingEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackingEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["eventDate"] = o.EventDate
	toSerialize["eventAddress"] = o.EventAddress
	toSerialize["eventCode"] = o.EventCode
	toSerialize["eventDescription"] = o.EventDescription

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TrackingEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eventDate",
		"eventAddress",
		"eventCode",
		"eventDescription",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrackingEvent := _TrackingEvent{}

	err = json.Unmarshal(data, &varTrackingEvent)

	if err != nil {
		return err
	}

	*o = TrackingEvent(varTrackingEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "eventDate")
		delete(additionalProperties, "eventAddress")
		delete(additionalProperties, "eventCode")
		delete(additionalProperties, "eventDescription")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTrackingEvent struct {
	value *TrackingEvent
	isSet bool
}

func (v NullableTrackingEvent) Get() *TrackingEvent {
	return v.value
}

func (v *NullableTrackingEvent) Set(val *TrackingEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackingEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackingEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackingEvent(val *TrackingEvent) *NullableTrackingEvent {
	return &NullableTrackingEvent{value: val, isSet: true}
}

func (v NullableTrackingEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackingEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


