/*
Selling Partner APIs for Fulfillment Outbound

The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

API version: 2020-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillmentoutbound20200701

import (
	"encoding/json"
	"fmt"
)

// EventCode The event code for the delivery event.
type EventCode string

// List of EventCode
const (
	EVENTCODE_EVENT_101 EventCode = "EVENT_101"
	EVENTCODE_EVENT_102 EventCode = "EVENT_102"
	EVENTCODE_EVENT_201 EventCode = "EVENT_201"
	EVENTCODE_EVENT_202 EventCode = "EVENT_202"
	EVENTCODE_EVENT_203 EventCode = "EVENT_203"
	EVENTCODE_EVENT_204 EventCode = "EVENT_204"
	EVENTCODE_EVENT_205 EventCode = "EVENT_205"
	EVENTCODE_EVENT_206 EventCode = "EVENT_206"
	EVENTCODE_EVENT_301 EventCode = "EVENT_301"
	EVENTCODE_EVENT_302 EventCode = "EVENT_302"
	EVENTCODE_EVENT_304 EventCode = "EVENT_304"
	EVENTCODE_EVENT_306 EventCode = "EVENT_306"
	EVENTCODE_EVENT_307 EventCode = "EVENT_307"
	EVENTCODE_EVENT_308 EventCode = "EVENT_308"
	EVENTCODE_EVENT_309 EventCode = "EVENT_309"
	EVENTCODE_EVENT_401 EventCode = "EVENT_401"
	EVENTCODE_EVENT_402 EventCode = "EVENT_402"
	EVENTCODE_EVENT_403 EventCode = "EVENT_403"
	EVENTCODE_EVENT_404 EventCode = "EVENT_404"
	EVENTCODE_EVENT_405 EventCode = "EVENT_405"
	EVENTCODE_EVENT_406 EventCode = "EVENT_406"
	EVENTCODE_EVENT_407 EventCode = "EVENT_407"
	EVENTCODE_EVENT_408 EventCode = "EVENT_408"
	EVENTCODE_EVENT_409 EventCode = "EVENT_409"
	EVENTCODE_EVENT_411 EventCode = "EVENT_411"
	EVENTCODE_EVENT_412 EventCode = "EVENT_412"
	EVENTCODE_EVENT_413 EventCode = "EVENT_413"
	EVENTCODE_EVENT_414 EventCode = "EVENT_414"
	EVENTCODE_EVENT_415 EventCode = "EVENT_415"
	EVENTCODE_EVENT_416 EventCode = "EVENT_416"
	EVENTCODE_EVENT_417 EventCode = "EVENT_417"
	EVENTCODE_EVENT_418 EventCode = "EVENT_418"
	EVENTCODE_EVENT_419 EventCode = "EVENT_419"
)

// All allowed values of EventCode enum
var AllowedEventCodeEnumValues = []EventCode{
	"EVENT_101",
	"EVENT_102",
	"EVENT_201",
	"EVENT_202",
	"EVENT_203",
	"EVENT_204",
	"EVENT_205",
	"EVENT_206",
	"EVENT_301",
	"EVENT_302",
	"EVENT_304",
	"EVENT_306",
	"EVENT_307",
	"EVENT_308",
	"EVENT_309",
	"EVENT_401",
	"EVENT_402",
	"EVENT_403",
	"EVENT_404",
	"EVENT_405",
	"EVENT_406",
	"EVENT_407",
	"EVENT_408",
	"EVENT_409",
	"EVENT_411",
	"EVENT_412",
	"EVENT_413",
	"EVENT_414",
	"EVENT_415",
	"EVENT_416",
	"EVENT_417",
	"EVENT_418",
	"EVENT_419",
}

func (v *EventCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EventCode(value)
	for _, existing := range AllowedEventCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EventCode", value)
}

// NewEventCodeFromValue returns a pointer to a valid EventCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEventCodeFromValue(v string) (*EventCode, error) {
	ev := EventCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EventCode: valid values are %v", v, AllowedEventCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EventCode) IsValid() bool {
	for _, existing := range AllowedEventCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EventCode value
func (v EventCode) Ptr() *EventCode {
	return &v
}

type NullableEventCode struct {
	value *EventCode
	isSet bool
}

func (v NullableEventCode) Get() *EventCode {
	return v.value
}

func (v *NullableEventCode) Set(val *EventCode) {
	v.value = val
	v.isSet = true
}

func (v NullableEventCode) IsSet() bool {
	return v.isSet
}

func (v *NullableEventCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventCode(val *EventCode) *NullableEventCode {
	return &NullableEventCode{value: val, isSet: true}
}

func (v NullableEventCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

