/*
Selling Partner APIs for Fulfillment Outbound

The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

API version: 2020-07-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillmentoutbound20200701

import (
	"encoding/json"
	"fmt"
)

// checks if the InvalidItemReason type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvalidItemReason{}

// InvalidItemReason The reason that the item is invalid for return.
type InvalidItemReason struct {
	InvalidItemReasonCode InvalidItemReasonCode `json:"invalidItemReasonCode"`
	// A human readable description of the invalid item reason code.
	Description string `json:"description"`
	AdditionalProperties map[string]interface{}
}

type _InvalidItemReason InvalidItemReason

// NewInvalidItemReason instantiates a new InvalidItemReason object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvalidItemReason(invalidItemReasonCode InvalidItemReasonCode, description string) *InvalidItemReason {
	this := InvalidItemReason{}
	this.InvalidItemReasonCode = invalidItemReasonCode
	this.Description = description
	return &this
}

// NewInvalidItemReasonWithDefaults instantiates a new InvalidItemReason object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvalidItemReasonWithDefaults() *InvalidItemReason {
	this := InvalidItemReason{}
	return &this
}

// GetInvalidItemReasonCode returns the InvalidItemReasonCode field value
func (o *InvalidItemReason) GetInvalidItemReasonCode() InvalidItemReasonCode {
	if o == nil {
		var ret InvalidItemReasonCode
		return ret
	}

	return o.InvalidItemReasonCode
}

// GetInvalidItemReasonCodeOk returns a tuple with the InvalidItemReasonCode field value
// and a boolean to check if the value has been set.
func (o *InvalidItemReason) GetInvalidItemReasonCodeOk() (*InvalidItemReasonCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvalidItemReasonCode, true
}

// SetInvalidItemReasonCode sets field value
func (o *InvalidItemReason) SetInvalidItemReasonCode(v InvalidItemReasonCode) {
	o.InvalidItemReasonCode = v
}

// GetDescription returns the Description field value
func (o *InvalidItemReason) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *InvalidItemReason) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *InvalidItemReason) SetDescription(v string) {
	o.Description = v
}

func (o InvalidItemReason) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvalidItemReason) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invalidItemReasonCode"] = o.InvalidItemReasonCode
	toSerialize["description"] = o.Description

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InvalidItemReason) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invalidItemReasonCode",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvalidItemReason := _InvalidItemReason{}

	err = json.Unmarshal(data, &varInvalidItemReason)

	if err != nil {
		return err
	}

	*o = InvalidItemReason(varInvalidItemReason)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "invalidItemReasonCode")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInvalidItemReason struct {
	value *InvalidItemReason
	isSet bool
}

func (v NullableInvalidItemReason) Get() *InvalidItemReason {
	return v.value
}

func (v *NullableInvalidItemReason) Set(val *InvalidItemReason) {
	v.value = val
	v.isSet = true
}

func (v NullableInvalidItemReason) IsSet() bool {
	return v.isSet
}

func (v *NullableInvalidItemReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvalidItemReason(val *InvalidItemReason) *NullableInvalidItemReason {
	return &NullableInvalidItemReason{value: val, isSet: true}
}

func (v NullableInvalidItemReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvalidItemReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


