/*
Selling Partner API for Direct Fulfillment Shipping

The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vendordirectfulfillmentshippingv1

import (
	"encoding/json"
)

// checks if the SubmitShippingLabelsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitShippingLabelsResponse{}

// SubmitShippingLabelsResponse The response schema for the submitShippingLabelRequest operation.
type SubmitShippingLabelsResponse struct {
	Payload *TransactionReference `json:"payload,omitempty"`
	// A list of error responses returned when a request is unsuccessful.
	Errors []Error `json:"errors,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SubmitShippingLabelsResponse SubmitShippingLabelsResponse

// NewSubmitShippingLabelsResponse instantiates a new SubmitShippingLabelsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitShippingLabelsResponse() *SubmitShippingLabelsResponse {
	this := SubmitShippingLabelsResponse{}
	return &this
}

// NewSubmitShippingLabelsResponseWithDefaults instantiates a new SubmitShippingLabelsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitShippingLabelsResponseWithDefaults() *SubmitShippingLabelsResponse {
	this := SubmitShippingLabelsResponse{}
	return &this
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *SubmitShippingLabelsResponse) GetPayload() TransactionReference {
	if o == nil || IsNil(o.Payload) {
		var ret TransactionReference
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitShippingLabelsResponse) GetPayloadOk() (*TransactionReference, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *SubmitShippingLabelsResponse) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given TransactionReference and assigns it to the Payload field.
func (o *SubmitShippingLabelsResponse) SetPayload(v TransactionReference) {
	o.Payload = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *SubmitShippingLabelsResponse) GetErrors() []Error {
	if o == nil || IsNil(o.Errors) {
		var ret []Error
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitShippingLabelsResponse) GetErrorsOk() ([]Error, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *SubmitShippingLabelsResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error and assigns it to the Errors field.
func (o *SubmitShippingLabelsResponse) SetErrors(v []Error) {
	o.Errors = v
}

func (o SubmitShippingLabelsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitShippingLabelsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubmitShippingLabelsResponse) UnmarshalJSON(data []byte) (err error) {
	varSubmitShippingLabelsResponse := _SubmitShippingLabelsResponse{}

	err = json.Unmarshal(data, &varSubmitShippingLabelsResponse)

	if err != nil {
		return err
	}

	*o = SubmitShippingLabelsResponse(varSubmitShippingLabelsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "payload")
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubmitShippingLabelsResponse struct {
	value *SubmitShippingLabelsResponse
	isSet bool
}

func (v NullableSubmitShippingLabelsResponse) Get() *SubmitShippingLabelsResponse {
	return v.value
}

func (v *NullableSubmitShippingLabelsResponse) Set(val *SubmitShippingLabelsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitShippingLabelsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitShippingLabelsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitShippingLabelsResponse(val *SubmitShippingLabelsResponse) *NullableSubmitShippingLabelsResponse {
	return &NullableSubmitShippingLabelsResponse{value: val, isSet: true}
}

func (v NullableSubmitShippingLabelsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitShippingLabelsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


