/*
Selling Partner API for Fulfillment Inbound

The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillmentinboundv0

import (
	"encoding/json"
)

// checks if the ASINPrepInstructions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ASINPrepInstructions{}

// ASINPrepInstructions Item preparation instructions to help with item sourcing decisions.
type ASINPrepInstructions struct {
	// The Amazon Standard Identification Number (ASIN) of the item.
	ASIN *string `json:"ASIN,omitempty"`
	BarcodeInstruction *BarcodeInstruction `json:"BarcodeInstruction,omitempty"`
	PrepGuidance *PrepGuidance `json:"PrepGuidance,omitempty"`
	// A list of preparation instructions to help with item sourcing decisions.
	PrepInstructionList []PrepInstruction `json:"PrepInstructionList,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ASINPrepInstructions ASINPrepInstructions

// NewASINPrepInstructions instantiates a new ASINPrepInstructions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewASINPrepInstructions() *ASINPrepInstructions {
	this := ASINPrepInstructions{}
	return &this
}

// NewASINPrepInstructionsWithDefaults instantiates a new ASINPrepInstructions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewASINPrepInstructionsWithDefaults() *ASINPrepInstructions {
	this := ASINPrepInstructions{}
	return &this
}

// GetASIN returns the ASIN field value if set, zero value otherwise.
func (o *ASINPrepInstructions) GetASIN() string {
	if o == nil || IsNil(o.ASIN) {
		var ret string
		return ret
	}
	return *o.ASIN
}

// GetASINOk returns a tuple with the ASIN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ASINPrepInstructions) GetASINOk() (*string, bool) {
	if o == nil || IsNil(o.ASIN) {
		return nil, false
	}
	return o.ASIN, true
}

// HasASIN returns a boolean if a field has been set.
func (o *ASINPrepInstructions) HasASIN() bool {
	if o != nil && !IsNil(o.ASIN) {
		return true
	}

	return false
}

// SetASIN gets a reference to the given string and assigns it to the ASIN field.
func (o *ASINPrepInstructions) SetASIN(v string) {
	o.ASIN = &v
}

// GetBarcodeInstruction returns the BarcodeInstruction field value if set, zero value otherwise.
func (o *ASINPrepInstructions) GetBarcodeInstruction() BarcodeInstruction {
	if o == nil || IsNil(o.BarcodeInstruction) {
		var ret BarcodeInstruction
		return ret
	}
	return *o.BarcodeInstruction
}

// GetBarcodeInstructionOk returns a tuple with the BarcodeInstruction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ASINPrepInstructions) GetBarcodeInstructionOk() (*BarcodeInstruction, bool) {
	if o == nil || IsNil(o.BarcodeInstruction) {
		return nil, false
	}
	return o.BarcodeInstruction, true
}

// HasBarcodeInstruction returns a boolean if a field has been set.
func (o *ASINPrepInstructions) HasBarcodeInstruction() bool {
	if o != nil && !IsNil(o.BarcodeInstruction) {
		return true
	}

	return false
}

// SetBarcodeInstruction gets a reference to the given BarcodeInstruction and assigns it to the BarcodeInstruction field.
func (o *ASINPrepInstructions) SetBarcodeInstruction(v BarcodeInstruction) {
	o.BarcodeInstruction = &v
}

// GetPrepGuidance returns the PrepGuidance field value if set, zero value otherwise.
func (o *ASINPrepInstructions) GetPrepGuidance() PrepGuidance {
	if o == nil || IsNil(o.PrepGuidance) {
		var ret PrepGuidance
		return ret
	}
	return *o.PrepGuidance
}

// GetPrepGuidanceOk returns a tuple with the PrepGuidance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ASINPrepInstructions) GetPrepGuidanceOk() (*PrepGuidance, bool) {
	if o == nil || IsNil(o.PrepGuidance) {
		return nil, false
	}
	return o.PrepGuidance, true
}

// HasPrepGuidance returns a boolean if a field has been set.
func (o *ASINPrepInstructions) HasPrepGuidance() bool {
	if o != nil && !IsNil(o.PrepGuidance) {
		return true
	}

	return false
}

// SetPrepGuidance gets a reference to the given PrepGuidance and assigns it to the PrepGuidance field.
func (o *ASINPrepInstructions) SetPrepGuidance(v PrepGuidance) {
	o.PrepGuidance = &v
}

// GetPrepInstructionList returns the PrepInstructionList field value if set, zero value otherwise.
func (o *ASINPrepInstructions) GetPrepInstructionList() []PrepInstruction {
	if o == nil || IsNil(o.PrepInstructionList) {
		var ret []PrepInstruction
		return ret
	}
	return o.PrepInstructionList
}

// GetPrepInstructionListOk returns a tuple with the PrepInstructionList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ASINPrepInstructions) GetPrepInstructionListOk() ([]PrepInstruction, bool) {
	if o == nil || IsNil(o.PrepInstructionList) {
		return nil, false
	}
	return o.PrepInstructionList, true
}

// HasPrepInstructionList returns a boolean if a field has been set.
func (o *ASINPrepInstructions) HasPrepInstructionList() bool {
	if o != nil && !IsNil(o.PrepInstructionList) {
		return true
	}

	return false
}

// SetPrepInstructionList gets a reference to the given []PrepInstruction and assigns it to the PrepInstructionList field.
func (o *ASINPrepInstructions) SetPrepInstructionList(v []PrepInstruction) {
	o.PrepInstructionList = v
}

func (o ASINPrepInstructions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ASINPrepInstructions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ASIN) {
		toSerialize["ASIN"] = o.ASIN
	}
	if !IsNil(o.BarcodeInstruction) {
		toSerialize["BarcodeInstruction"] = o.BarcodeInstruction
	}
	if !IsNil(o.PrepGuidance) {
		toSerialize["PrepGuidance"] = o.PrepGuidance
	}
	if !IsNil(o.PrepInstructionList) {
		toSerialize["PrepInstructionList"] = o.PrepInstructionList
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ASINPrepInstructions) UnmarshalJSON(data []byte) (err error) {
	varASINPrepInstructions := _ASINPrepInstructions{}

	err = json.Unmarshal(data, &varASINPrepInstructions)

	if err != nil {
		return err
	}

	*o = ASINPrepInstructions(varASINPrepInstructions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ASIN")
		delete(additionalProperties, "BarcodeInstruction")
		delete(additionalProperties, "PrepGuidance")
		delete(additionalProperties, "PrepInstructionList")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableASINPrepInstructions struct {
	value *ASINPrepInstructions
	isSet bool
}

func (v NullableASINPrepInstructions) Get() *ASINPrepInstructions {
	return v.value
}

func (v *NullableASINPrepInstructions) Set(val *ASINPrepInstructions) {
	v.value = val
	v.isSet = true
}

func (v NullableASINPrepInstructions) IsSet() bool {
	return v.isSet
}

func (v *NullableASINPrepInstructions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableASINPrepInstructions(val *ASINPrepInstructions) *NullableASINPrepInstructions {
	return &NullableASINPrepInstructions{value: val, isSet: true}
}

func (v NullableASINPrepInstructions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableASINPrepInstructions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


