/*
Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data

The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.

API version: 2021-10-28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vendordirectfulfillmentsandboxdata20211028

import (
	"encoding/json"
	"fmt"
)

// checks if the OrderScenarioRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderScenarioRequest{}

// OrderScenarioRequest The party identifiers required to generate the test data.
type OrderScenarioRequest struct {
	SellingParty PartyIdentification `json:"sellingParty"`
	ShipFromParty PartyIdentification `json:"shipFromParty"`
	AdditionalProperties map[string]interface{}
}

type _OrderScenarioRequest OrderScenarioRequest

// NewOrderScenarioRequest instantiates a new OrderScenarioRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderScenarioRequest(sellingParty PartyIdentification, shipFromParty PartyIdentification) *OrderScenarioRequest {
	this := OrderScenarioRequest{}
	this.SellingParty = sellingParty
	this.ShipFromParty = shipFromParty
	return &this
}

// NewOrderScenarioRequestWithDefaults instantiates a new OrderScenarioRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderScenarioRequestWithDefaults() *OrderScenarioRequest {
	this := OrderScenarioRequest{}
	return &this
}

// GetSellingParty returns the SellingParty field value
func (o *OrderScenarioRequest) GetSellingParty() PartyIdentification {
	if o == nil {
		var ret PartyIdentification
		return ret
	}

	return o.SellingParty
}

// GetSellingPartyOk returns a tuple with the SellingParty field value
// and a boolean to check if the value has been set.
func (o *OrderScenarioRequest) GetSellingPartyOk() (*PartyIdentification, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SellingParty, true
}

// SetSellingParty sets field value
func (o *OrderScenarioRequest) SetSellingParty(v PartyIdentification) {
	o.SellingParty = v
}

// GetShipFromParty returns the ShipFromParty field value
func (o *OrderScenarioRequest) GetShipFromParty() PartyIdentification {
	if o == nil {
		var ret PartyIdentification
		return ret
	}

	return o.ShipFromParty
}

// GetShipFromPartyOk returns a tuple with the ShipFromParty field value
// and a boolean to check if the value has been set.
func (o *OrderScenarioRequest) GetShipFromPartyOk() (*PartyIdentification, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipFromParty, true
}

// SetShipFromParty sets field value
func (o *OrderScenarioRequest) SetShipFromParty(v PartyIdentification) {
	o.ShipFromParty = v
}

func (o OrderScenarioRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderScenarioRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sellingParty"] = o.SellingParty
	toSerialize["shipFromParty"] = o.ShipFromParty

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderScenarioRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sellingParty",
		"shipFromParty",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderScenarioRequest := _OrderScenarioRequest{}

	err = json.Unmarshal(data, &varOrderScenarioRequest)

	if err != nil {
		return err
	}

	*o = OrderScenarioRequest(varOrderScenarioRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "sellingParty")
		delete(additionalProperties, "shipFromParty")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderScenarioRequest struct {
	value *OrderScenarioRequest
	isSet bool
}

func (v NullableOrderScenarioRequest) Get() *OrderScenarioRequest {
	return v.value
}

func (v *NullableOrderScenarioRequest) Set(val *OrderScenarioRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderScenarioRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderScenarioRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderScenarioRequest(val *OrderScenarioRequest) *NullableOrderScenarioRequest {
	return &NullableOrderScenarioRequest{value: val, isSet: true}
}

func (v NullableOrderScenarioRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderScenarioRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


