/*
Selling Partner API for Solicitations

With the Solicitations API you can build applications that send non-critical solicitations to buyers. You can get a list of solicitation types that are available for an order that you specify, then call an operation that sends a solicitation to the buyer for that order. Buyers cannot respond to solicitations sent by this API, and these solicitations do not appear in the Messaging section of Seller Central or in the recipient's Message Center. The Solicitations API returns responses that are formed according to the <a href=https://tools.ietf.org/html/draft-kelly-json-hal-08>JSON Hypertext Application Language</a> (HAL) standard.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package solicitations

import (
	"encoding/json"
	"fmt"
)

// checks if the GetSolicitationActionsForOrderResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSolicitationActionsForOrderResponseLinks{}

// GetSolicitationActionsForOrderResponseLinks struct for GetSolicitationActionsForOrderResponseLinks
type GetSolicitationActionsForOrderResponseLinks struct {
	Self LinkObject `json:"self"`
	// Eligible actions for the specified amazonOrderId.
	Actions []LinkObject `json:"actions"`
	AdditionalProperties map[string]interface{}
}

type _GetSolicitationActionsForOrderResponseLinks GetSolicitationActionsForOrderResponseLinks

// NewGetSolicitationActionsForOrderResponseLinks instantiates a new GetSolicitationActionsForOrderResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSolicitationActionsForOrderResponseLinks(self LinkObject, actions []LinkObject) *GetSolicitationActionsForOrderResponseLinks {
	this := GetSolicitationActionsForOrderResponseLinks{}
	this.Self = self
	this.Actions = actions
	return &this
}

// NewGetSolicitationActionsForOrderResponseLinksWithDefaults instantiates a new GetSolicitationActionsForOrderResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSolicitationActionsForOrderResponseLinksWithDefaults() *GetSolicitationActionsForOrderResponseLinks {
	this := GetSolicitationActionsForOrderResponseLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *GetSolicitationActionsForOrderResponseLinks) GetSelf() LinkObject {
	if o == nil {
		var ret LinkObject
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *GetSolicitationActionsForOrderResponseLinks) GetSelfOk() (*LinkObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *GetSolicitationActionsForOrderResponseLinks) SetSelf(v LinkObject) {
	o.Self = v
}

// GetActions returns the Actions field value
func (o *GetSolicitationActionsForOrderResponseLinks) GetActions() []LinkObject {
	if o == nil {
		var ret []LinkObject
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *GetSolicitationActionsForOrderResponseLinks) GetActionsOk() ([]LinkObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *GetSolicitationActionsForOrderResponseLinks) SetActions(v []LinkObject) {
	o.Actions = v
}

func (o GetSolicitationActionsForOrderResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSolicitationActionsForOrderResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	toSerialize["actions"] = o.Actions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSolicitationActionsForOrderResponseLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSolicitationActionsForOrderResponseLinks := _GetSolicitationActionsForOrderResponseLinks{}

	err = json.Unmarshal(data, &varGetSolicitationActionsForOrderResponseLinks)

	if err != nil {
		return err
	}

	*o = GetSolicitationActionsForOrderResponseLinks(varGetSolicitationActionsForOrderResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "self")
		delete(additionalProperties, "actions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSolicitationActionsForOrderResponseLinks struct {
	value *GetSolicitationActionsForOrderResponseLinks
	isSet bool
}

func (v NullableGetSolicitationActionsForOrderResponseLinks) Get() *GetSolicitationActionsForOrderResponseLinks {
	return v.value
}

func (v *NullableGetSolicitationActionsForOrderResponseLinks) Set(val *GetSolicitationActionsForOrderResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSolicitationActionsForOrderResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSolicitationActionsForOrderResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSolicitationActionsForOrderResponseLinks(val *GetSolicitationActionsForOrderResponseLinks) *NullableGetSolicitationActionsForOrderResponseLinks {
	return &NullableGetSolicitationActionsForOrderResponseLinks{value: val, isSet: true}
}

func (v NullableGetSolicitationActionsForOrderResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSolicitationActionsForOrderResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


