/*
Selling Partner API for Services

With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package services

import (
	"encoding/json"
	"time"
	"fmt"

	"github.com/brendan-hurley/spapi-go/flextime"
)

// checks if the DateTimeRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DateTimeRange{}

// DateTimeRange A range of time.
type DateTimeRange struct {
	// The beginning of the time range. Must be in UTC in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
	StartTime flextime.FlexTime `json:"startTime"`
	// The end of the time range. Must be in UTC in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
	EndTime flextime.FlexTime `json:"endTime"`
	AdditionalProperties map[string]interface{}
}

type _DateTimeRange DateTimeRange

// NewDateTimeRange instantiates a new DateTimeRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDateTimeRange(startTime time.Time, endTime time.Time) *DateTimeRange {
	this := DateTimeRange{}
	this.StartTime = flextime.FlexTime{Time: startTime}
	this.EndTime = flextime.FlexTime{Time: endTime}
	return &this
}

// NewDateTimeRangeWithDefaults instantiates a new DateTimeRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDateTimeRangeWithDefaults() *DateTimeRange {
	this := DateTimeRange{}
	return &this
}

// GetStartTime returns the StartTime field value
func (o *DateTimeRange) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime.Time
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *DateTimeRange) GetStartTimeOk() (*flextime.FlexTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *DateTimeRange) SetStartTime(v time.Time) {
	o.StartTime = flextime.FlexTime{Time: v}
}

// GetEndTime returns the EndTime field value
func (o *DateTimeRange) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime.Time
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *DateTimeRange) GetEndTimeOk() (*flextime.FlexTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *DateTimeRange) SetEndTime(v time.Time) {
	o.EndTime = flextime.FlexTime{Time: v}
}

func (o DateTimeRange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DateTimeRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["startTime"] = o.StartTime
	toSerialize["endTime"] = o.EndTime

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DateTimeRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"startTime",
		"endTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDateTimeRange := _DateTimeRange{}

	err = json.Unmarshal(data, &varDateTimeRange)

	if err != nil {
		return err
	}

	*o = DateTimeRange(varDateTimeRange)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "startTime")
		delete(additionalProperties, "endTime")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDateTimeRange struct {
	value *DateTimeRange
	isSet bool
}

func (v NullableDateTimeRange) Get() *DateTimeRange {
	return v.value
}

func (v *NullableDateTimeRange) Set(val *DateTimeRange) {
	v.value = val
	v.isSet = true
}

func (v NullableDateTimeRange) IsSet() bool {
	return v.isSet
}

func (v *NullableDateTimeRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDateTimeRange(val *DateTimeRange) *NullableDateTimeRange {
	return &NullableDateTimeRange{value: val, isSet: true}
}

func (v NullableDateTimeRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDateTimeRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


