/*
Selling Partner API for A+ Content Management

Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.

API version: 2020-11-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apluscontent20201101

import (
	"encoding/json"
	"fmt"
)

// checks if the StandardCompanyLogoModule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandardCompanyLogoModule{}

// StandardCompanyLogoModule The standard company logo image.
type StandardCompanyLogoModule struct {
	CompanyLogo ImageComponent `json:"companyLogo"`
	AdditionalProperties map[string]interface{}
}

type _StandardCompanyLogoModule StandardCompanyLogoModule

// NewStandardCompanyLogoModule instantiates a new StandardCompanyLogoModule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandardCompanyLogoModule(companyLogo ImageComponent) *StandardCompanyLogoModule {
	this := StandardCompanyLogoModule{}
	this.CompanyLogo = companyLogo
	return &this
}

// NewStandardCompanyLogoModuleWithDefaults instantiates a new StandardCompanyLogoModule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandardCompanyLogoModuleWithDefaults() *StandardCompanyLogoModule {
	this := StandardCompanyLogoModule{}
	return &this
}

// GetCompanyLogo returns the CompanyLogo field value
func (o *StandardCompanyLogoModule) GetCompanyLogo() ImageComponent {
	if o == nil {
		var ret ImageComponent
		return ret
	}

	return o.CompanyLogo
}

// GetCompanyLogoOk returns a tuple with the CompanyLogo field value
// and a boolean to check if the value has been set.
func (o *StandardCompanyLogoModule) GetCompanyLogoOk() (*ImageComponent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyLogo, true
}

// SetCompanyLogo sets field value
func (o *StandardCompanyLogoModule) SetCompanyLogo(v ImageComponent) {
	o.CompanyLogo = v
}

func (o StandardCompanyLogoModule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandardCompanyLogoModule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["companyLogo"] = o.CompanyLogo

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StandardCompanyLogoModule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"companyLogo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStandardCompanyLogoModule := _StandardCompanyLogoModule{}

	err = json.Unmarshal(data, &varStandardCompanyLogoModule)

	if err != nil {
		return err
	}

	*o = StandardCompanyLogoModule(varStandardCompanyLogoModule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "companyLogo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStandardCompanyLogoModule struct {
	value *StandardCompanyLogoModule
	isSet bool
}

func (v NullableStandardCompanyLogoModule) Get() *StandardCompanyLogoModule {
	return v.value
}

func (v *NullableStandardCompanyLogoModule) Set(val *StandardCompanyLogoModule) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardCompanyLogoModule) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardCompanyLogoModule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardCompanyLogoModule(val *StandardCompanyLogoModule) *NullableStandardCompanyLogoModule {
	return &NullableStandardCompanyLogoModule{value: val, isSet: true}
}

func (v NullableStandardCompanyLogoModule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardCompanyLogoModule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


