/*
Selling Partner API for A+ Content Management

Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.

API version: 2020-11-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apluscontent20201101

import (
	"encoding/json"
	"fmt"
)

// checks if the ListContentDocumentAsinRelationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListContentDocumentAsinRelationsResponse{}

// ListContentDocumentAsinRelationsResponse struct for ListContentDocumentAsinRelationsResponse
type ListContentDocumentAsinRelationsResponse struct {
	// A set of messages to the user, such as warnings or comments.
	Warnings []Error `json:"warnings,omitempty"`
	// A token that you use to fetch a specific page when there are multiple pages of results.
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// The set of ASIN metadata.
	AsinMetadataSet []AsinMetadata `json:"asinMetadataSet"`
	AdditionalProperties map[string]interface{}
}

type _ListContentDocumentAsinRelationsResponse ListContentDocumentAsinRelationsResponse

// NewListContentDocumentAsinRelationsResponse instantiates a new ListContentDocumentAsinRelationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListContentDocumentAsinRelationsResponse(asinMetadataSet []AsinMetadata) *ListContentDocumentAsinRelationsResponse {
	this := ListContentDocumentAsinRelationsResponse{}
	this.AsinMetadataSet = asinMetadataSet
	return &this
}

// NewListContentDocumentAsinRelationsResponseWithDefaults instantiates a new ListContentDocumentAsinRelationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListContentDocumentAsinRelationsResponseWithDefaults() *ListContentDocumentAsinRelationsResponse {
	this := ListContentDocumentAsinRelationsResponse{}
	return &this
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *ListContentDocumentAsinRelationsResponse) GetWarnings() []Error {
	if o == nil || IsNil(o.Warnings) {
		var ret []Error
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContentDocumentAsinRelationsResponse) GetWarningsOk() ([]Error, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *ListContentDocumentAsinRelationsResponse) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []Error and assigns it to the Warnings field.
func (o *ListContentDocumentAsinRelationsResponse) SetWarnings(v []Error) {
	o.Warnings = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListContentDocumentAsinRelationsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContentDocumentAsinRelationsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListContentDocumentAsinRelationsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListContentDocumentAsinRelationsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetAsinMetadataSet returns the AsinMetadataSet field value
func (o *ListContentDocumentAsinRelationsResponse) GetAsinMetadataSet() []AsinMetadata {
	if o == nil {
		var ret []AsinMetadata
		return ret
	}

	return o.AsinMetadataSet
}

// GetAsinMetadataSetOk returns a tuple with the AsinMetadataSet field value
// and a boolean to check if the value has been set.
func (o *ListContentDocumentAsinRelationsResponse) GetAsinMetadataSetOk() ([]AsinMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.AsinMetadataSet, true
}

// SetAsinMetadataSet sets field value
func (o *ListContentDocumentAsinRelationsResponse) SetAsinMetadataSet(v []AsinMetadata) {
	o.AsinMetadataSet = v
}

func (o ListContentDocumentAsinRelationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListContentDocumentAsinRelationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	toSerialize["asinMetadataSet"] = o.AsinMetadataSet

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListContentDocumentAsinRelationsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asinMetadataSet",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListContentDocumentAsinRelationsResponse := _ListContentDocumentAsinRelationsResponse{}

	err = json.Unmarshal(data, &varListContentDocumentAsinRelationsResponse)

	if err != nil {
		return err
	}

	*o = ListContentDocumentAsinRelationsResponse(varListContentDocumentAsinRelationsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "warnings")
		delete(additionalProperties, "nextPageToken")
		delete(additionalProperties, "asinMetadataSet")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListContentDocumentAsinRelationsResponse struct {
	value *ListContentDocumentAsinRelationsResponse
	isSet bool
}

func (v NullableListContentDocumentAsinRelationsResponse) Get() *ListContentDocumentAsinRelationsResponse {
	return v.value
}

func (v *NullableListContentDocumentAsinRelationsResponse) Set(val *ListContentDocumentAsinRelationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListContentDocumentAsinRelationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListContentDocumentAsinRelationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListContentDocumentAsinRelationsResponse(val *ListContentDocumentAsinRelationsResponse) *NullableListContentDocumentAsinRelationsResponse {
	return &NullableListContentDocumentAsinRelationsResponse{value: val, isSet: true}
}

func (v NullableListContentDocumentAsinRelationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListContentDocumentAsinRelationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


