/*
Selling Partner API for A+ Content Management

Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.

API version: 2020-11-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apluscontent20201101

import (
	"encoding/json"
	"fmt"
)

// checks if the ImageOffsets type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageOffsets{}

// ImageOffsets The top left corner of the cropped image, specified in the original image's coordinate space.
type ImageOffsets struct {
	X IntegerWithUnits `json:"x"`
	Y IntegerWithUnits `json:"y"`
	AdditionalProperties map[string]interface{}
}

type _ImageOffsets ImageOffsets

// NewImageOffsets instantiates a new ImageOffsets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageOffsets(x IntegerWithUnits, y IntegerWithUnits) *ImageOffsets {
	this := ImageOffsets{}
	this.X = x
	this.Y = y
	return &this
}

// NewImageOffsetsWithDefaults instantiates a new ImageOffsets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageOffsetsWithDefaults() *ImageOffsets {
	this := ImageOffsets{}
	return &this
}

// GetX returns the X field value
func (o *ImageOffsets) GetX() IntegerWithUnits {
	if o == nil {
		var ret IntegerWithUnits
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *ImageOffsets) GetXOk() (*IntegerWithUnits, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *ImageOffsets) SetX(v IntegerWithUnits) {
	o.X = v
}

// GetY returns the Y field value
func (o *ImageOffsets) GetY() IntegerWithUnits {
	if o == nil {
		var ret IntegerWithUnits
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *ImageOffsets) GetYOk() (*IntegerWithUnits, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *ImageOffsets) SetY(v IntegerWithUnits) {
	o.Y = v
}

func (o ImageOffsets) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageOffsets) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ImageOffsets) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x",
		"y",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageOffsets := _ImageOffsets{}

	err = json.Unmarshal(data, &varImageOffsets)

	if err != nil {
		return err
	}

	*o = ImageOffsets(varImageOffsets)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "x")
		delete(additionalProperties, "y")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableImageOffsets struct {
	value *ImageOffsets
	isSet bool
}

func (v NullableImageOffsets) Get() *ImageOffsets {
	return v.value
}

func (v *NullableImageOffsets) Set(val *ImageOffsets) {
	v.value = val
	v.isSet = true
}

func (v NullableImageOffsets) IsSet() bool {
	return v.isSet
}

func (v *NullableImageOffsets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageOffsets(val *ImageOffsets) *NullableImageOffsets {
	return &NullableImageOffsets{value: val, isSet: true}
}

func (v NullableImageOffsets) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageOffsets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


