/*
Selling Partner API for A+ Content Management

Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.

API version: 2020-11-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apluscontent20201101

import (
	"encoding/json"
)

// checks if the StandardSingleImageHighlightsModule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandardSingleImageHighlightsModule{}

// StandardSingleImageHighlightsModule A standard image with several paragraphs and a bulleted list.
type StandardSingleImageHighlightsModule struct {
	Image *ImageComponent `json:"image,omitempty"`
	Headline *TextComponent `json:"headline,omitempty"`
	TextBlock1 *StandardTextBlock `json:"textBlock1,omitempty"`
	TextBlock2 *StandardTextBlock `json:"textBlock2,omitempty"`
	TextBlock3 *StandardTextBlock `json:"textBlock3,omitempty"`
	BulletedListBlock *StandardHeaderTextListBlock `json:"bulletedListBlock,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StandardSingleImageHighlightsModule StandardSingleImageHighlightsModule

// NewStandardSingleImageHighlightsModule instantiates a new StandardSingleImageHighlightsModule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandardSingleImageHighlightsModule() *StandardSingleImageHighlightsModule {
	this := StandardSingleImageHighlightsModule{}
	return &this
}

// NewStandardSingleImageHighlightsModuleWithDefaults instantiates a new StandardSingleImageHighlightsModule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandardSingleImageHighlightsModuleWithDefaults() *StandardSingleImageHighlightsModule {
	this := StandardSingleImageHighlightsModule{}
	return &this
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *StandardSingleImageHighlightsModule) GetImage() ImageComponent {
	if o == nil || IsNil(o.Image) {
		var ret ImageComponent
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandardSingleImageHighlightsModule) GetImageOk() (*ImageComponent, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *StandardSingleImageHighlightsModule) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given ImageComponent and assigns it to the Image field.
func (o *StandardSingleImageHighlightsModule) SetImage(v ImageComponent) {
	o.Image = &v
}

// GetHeadline returns the Headline field value if set, zero value otherwise.
func (o *StandardSingleImageHighlightsModule) GetHeadline() TextComponent {
	if o == nil || IsNil(o.Headline) {
		var ret TextComponent
		return ret
	}
	return *o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandardSingleImageHighlightsModule) GetHeadlineOk() (*TextComponent, bool) {
	if o == nil || IsNil(o.Headline) {
		return nil, false
	}
	return o.Headline, true
}

// HasHeadline returns a boolean if a field has been set.
func (o *StandardSingleImageHighlightsModule) HasHeadline() bool {
	if o != nil && !IsNil(o.Headline) {
		return true
	}

	return false
}

// SetHeadline gets a reference to the given TextComponent and assigns it to the Headline field.
func (o *StandardSingleImageHighlightsModule) SetHeadline(v TextComponent) {
	o.Headline = &v
}

// GetTextBlock1 returns the TextBlock1 field value if set, zero value otherwise.
func (o *StandardSingleImageHighlightsModule) GetTextBlock1() StandardTextBlock {
	if o == nil || IsNil(o.TextBlock1) {
		var ret StandardTextBlock
		return ret
	}
	return *o.TextBlock1
}

// GetTextBlock1Ok returns a tuple with the TextBlock1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandardSingleImageHighlightsModule) GetTextBlock1Ok() (*StandardTextBlock, bool) {
	if o == nil || IsNil(o.TextBlock1) {
		return nil, false
	}
	return o.TextBlock1, true
}

// HasTextBlock1 returns a boolean if a field has been set.
func (o *StandardSingleImageHighlightsModule) HasTextBlock1() bool {
	if o != nil && !IsNil(o.TextBlock1) {
		return true
	}

	return false
}

// SetTextBlock1 gets a reference to the given StandardTextBlock and assigns it to the TextBlock1 field.
func (o *StandardSingleImageHighlightsModule) SetTextBlock1(v StandardTextBlock) {
	o.TextBlock1 = &v
}

// GetTextBlock2 returns the TextBlock2 field value if set, zero value otherwise.
func (o *StandardSingleImageHighlightsModule) GetTextBlock2() StandardTextBlock {
	if o == nil || IsNil(o.TextBlock2) {
		var ret StandardTextBlock
		return ret
	}
	return *o.TextBlock2
}

// GetTextBlock2Ok returns a tuple with the TextBlock2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandardSingleImageHighlightsModule) GetTextBlock2Ok() (*StandardTextBlock, bool) {
	if o == nil || IsNil(o.TextBlock2) {
		return nil, false
	}
	return o.TextBlock2, true
}

// HasTextBlock2 returns a boolean if a field has been set.
func (o *StandardSingleImageHighlightsModule) HasTextBlock2() bool {
	if o != nil && !IsNil(o.TextBlock2) {
		return true
	}

	return false
}

// SetTextBlock2 gets a reference to the given StandardTextBlock and assigns it to the TextBlock2 field.
func (o *StandardSingleImageHighlightsModule) SetTextBlock2(v StandardTextBlock) {
	o.TextBlock2 = &v
}

// GetTextBlock3 returns the TextBlock3 field value if set, zero value otherwise.
func (o *StandardSingleImageHighlightsModule) GetTextBlock3() StandardTextBlock {
	if o == nil || IsNil(o.TextBlock3) {
		var ret StandardTextBlock
		return ret
	}
	return *o.TextBlock3
}

// GetTextBlock3Ok returns a tuple with the TextBlock3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandardSingleImageHighlightsModule) GetTextBlock3Ok() (*StandardTextBlock, bool) {
	if o == nil || IsNil(o.TextBlock3) {
		return nil, false
	}
	return o.TextBlock3, true
}

// HasTextBlock3 returns a boolean if a field has been set.
func (o *StandardSingleImageHighlightsModule) HasTextBlock3() bool {
	if o != nil && !IsNil(o.TextBlock3) {
		return true
	}

	return false
}

// SetTextBlock3 gets a reference to the given StandardTextBlock and assigns it to the TextBlock3 field.
func (o *StandardSingleImageHighlightsModule) SetTextBlock3(v StandardTextBlock) {
	o.TextBlock3 = &v
}

// GetBulletedListBlock returns the BulletedListBlock field value if set, zero value otherwise.
func (o *StandardSingleImageHighlightsModule) GetBulletedListBlock() StandardHeaderTextListBlock {
	if o == nil || IsNil(o.BulletedListBlock) {
		var ret StandardHeaderTextListBlock
		return ret
	}
	return *o.BulletedListBlock
}

// GetBulletedListBlockOk returns a tuple with the BulletedListBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandardSingleImageHighlightsModule) GetBulletedListBlockOk() (*StandardHeaderTextListBlock, bool) {
	if o == nil || IsNil(o.BulletedListBlock) {
		return nil, false
	}
	return o.BulletedListBlock, true
}

// HasBulletedListBlock returns a boolean if a field has been set.
func (o *StandardSingleImageHighlightsModule) HasBulletedListBlock() bool {
	if o != nil && !IsNil(o.BulletedListBlock) {
		return true
	}

	return false
}

// SetBulletedListBlock gets a reference to the given StandardHeaderTextListBlock and assigns it to the BulletedListBlock field.
func (o *StandardSingleImageHighlightsModule) SetBulletedListBlock(v StandardHeaderTextListBlock) {
	o.BulletedListBlock = &v
}

func (o StandardSingleImageHighlightsModule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandardSingleImageHighlightsModule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Headline) {
		toSerialize["headline"] = o.Headline
	}
	if !IsNil(o.TextBlock1) {
		toSerialize["textBlock1"] = o.TextBlock1
	}
	if !IsNil(o.TextBlock2) {
		toSerialize["textBlock2"] = o.TextBlock2
	}
	if !IsNil(o.TextBlock3) {
		toSerialize["textBlock3"] = o.TextBlock3
	}
	if !IsNil(o.BulletedListBlock) {
		toSerialize["bulletedListBlock"] = o.BulletedListBlock
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StandardSingleImageHighlightsModule) UnmarshalJSON(data []byte) (err error) {
	varStandardSingleImageHighlightsModule := _StandardSingleImageHighlightsModule{}

	err = json.Unmarshal(data, &varStandardSingleImageHighlightsModule)

	if err != nil {
		return err
	}

	*o = StandardSingleImageHighlightsModule(varStandardSingleImageHighlightsModule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "image")
		delete(additionalProperties, "headline")
		delete(additionalProperties, "textBlock1")
		delete(additionalProperties, "textBlock2")
		delete(additionalProperties, "textBlock3")
		delete(additionalProperties, "bulletedListBlock")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStandardSingleImageHighlightsModule struct {
	value *StandardSingleImageHighlightsModule
	isSet bool
}

func (v NullableStandardSingleImageHighlightsModule) Get() *StandardSingleImageHighlightsModule {
	return v.value
}

func (v *NullableStandardSingleImageHighlightsModule) Set(val *StandardSingleImageHighlightsModule) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardSingleImageHighlightsModule) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardSingleImageHighlightsModule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardSingleImageHighlightsModule(val *StandardSingleImageHighlightsModule) *NullableStandardSingleImageHighlightsModule {
	return &NullableStandardSingleImageHighlightsModule{value: val, isSet: true}
}

func (v NullableStandardSingleImageHighlightsModule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardSingleImageHighlightsModule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


