/*
Selling Partner API for Shipment Invoicing

The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shipmentinvoicingv0

import (
	"encoding/json"
	"fmt"
)

// ShipmentInvoiceStatus The shipment invoice status.
type ShipmentInvoiceStatus string

// List of ShipmentInvoiceStatus
const (
	SHIPMENTINVOICESTATUS_PROCESSING ShipmentInvoiceStatus = "Processing"
	SHIPMENTINVOICESTATUS_ACCEPTED ShipmentInvoiceStatus = "Accepted"
	SHIPMENTINVOICESTATUS_ERRORED ShipmentInvoiceStatus = "Errored"
	SHIPMENTINVOICESTATUS_NOT_FOUND ShipmentInvoiceStatus = "NotFound"
)

// All allowed values of ShipmentInvoiceStatus enum
var AllowedShipmentInvoiceStatusEnumValues = []ShipmentInvoiceStatus{
	"Processing",
	"Accepted",
	"Errored",
	"NotFound",
}

func (v *ShipmentInvoiceStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ShipmentInvoiceStatus(value)
	for _, existing := range AllowedShipmentInvoiceStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ShipmentInvoiceStatus", value)
}

// NewShipmentInvoiceStatusFromValue returns a pointer to a valid ShipmentInvoiceStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewShipmentInvoiceStatusFromValue(v string) (*ShipmentInvoiceStatus, error) {
	ev := ShipmentInvoiceStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ShipmentInvoiceStatus: valid values are %v", v, AllowedShipmentInvoiceStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ShipmentInvoiceStatus) IsValid() bool {
	for _, existing := range AllowedShipmentInvoiceStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ShipmentInvoiceStatus value
func (v ShipmentInvoiceStatus) Ptr() *ShipmentInvoiceStatus {
	return &v
}

type NullableShipmentInvoiceStatus struct {
	value *ShipmentInvoiceStatus
	isSet bool
}

func (v NullableShipmentInvoiceStatus) Get() *ShipmentInvoiceStatus {
	return v.value
}

func (v *NullableShipmentInvoiceStatus) Set(val *ShipmentInvoiceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentInvoiceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentInvoiceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentInvoiceStatus(val *ShipmentInvoiceStatus) *NullableShipmentInvoiceStatus {
	return &NullableShipmentInvoiceStatus{value: val, isSet: true}
}

func (v NullableShipmentInvoiceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentInvoiceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

