/*
Selling Partner API for Direct Fulfillment Orders

The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.

API version: 2021-12-28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package vendordirectfulfillmentorders20211228

import (
	"encoding/json"
	"time"
	"fmt"

	"github.com/brendan-hurley/spapi-go/flextime"
)

// checks if the ShipmentDates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShipmentDates{}

// ShipmentDates Shipment dates.
type ShipmentDates struct {
	// Time by which the vendor is required to ship the order.
	RequiredShipDate flextime.FlexTime `json:"requiredShipDate"`
	// Delivery date promised to the Amazon customer.
	PromisedDeliveryDate *flextime.FlexTime `json:"promisedDeliveryDate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ShipmentDates ShipmentDates

// NewShipmentDates instantiates a new ShipmentDates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipmentDates(requiredShipDate time.Time) *ShipmentDates {
	this := ShipmentDates{}
	this.RequiredShipDate = flextime.FlexTime{Time: requiredShipDate}
	return &this
}

// NewShipmentDatesWithDefaults instantiates a new ShipmentDates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipmentDatesWithDefaults() *ShipmentDates {
	this := ShipmentDates{}
	return &this
}

// GetRequiredShipDate returns the RequiredShipDate field value
func (o *ShipmentDates) GetRequiredShipDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RequiredShipDate.Time
}

// GetRequiredShipDateOk returns a tuple with the RequiredShipDate field value
// and a boolean to check if the value has been set.
func (o *ShipmentDates) GetRequiredShipDateOk() (*flextime.FlexTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiredShipDate, true
}

// SetRequiredShipDate sets field value
func (o *ShipmentDates) SetRequiredShipDate(v time.Time) {
	o.RequiredShipDate = flextime.FlexTime{Time: v}
}

// GetPromisedDeliveryDate returns the PromisedDeliveryDate field value if set, zero value otherwise.
func (o *ShipmentDates) GetPromisedDeliveryDate() time.Time {
	if o == nil || IsNil(o.PromisedDeliveryDate) {
		var ret time.Time
		return ret
	}
	return o.PromisedDeliveryDate.Time
}

// GetPromisedDeliveryDateOk returns a tuple with the PromisedDeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentDates) GetPromisedDeliveryDateOk() (*flextime.FlexTime, bool) {
	if o == nil || IsNil(o.PromisedDeliveryDate) {
		return nil, false
	}
	return o.PromisedDeliveryDate, true
}

// HasPromisedDeliveryDate returns a boolean if a field has been set.
func (o *ShipmentDates) HasPromisedDeliveryDate() bool {
	if o != nil && !IsNil(o.PromisedDeliveryDate) {
		return true
	}

	return false
}

// SetPromisedDeliveryDate gets a reference to the given time.Time and assigns it to the PromisedDeliveryDate field.
func (o *ShipmentDates) SetPromisedDeliveryDate(v time.Time) {
	o.PromisedDeliveryDate = flextime.PtrFlexTime(v)
}

func (o ShipmentDates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShipmentDates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requiredShipDate"] = o.RequiredShipDate
	if !IsNil(o.PromisedDeliveryDate) {
		toSerialize["promisedDeliveryDate"] = o.PromisedDeliveryDate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ShipmentDates) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requiredShipDate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShipmentDates := _ShipmentDates{}

	err = json.Unmarshal(data, &varShipmentDates)

	if err != nil {
		return err
	}

	*o = ShipmentDates(varShipmentDates)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requiredShipDate")
		delete(additionalProperties, "promisedDeliveryDate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableShipmentDates struct {
	value *ShipmentDates
	isSet bool
}

func (v NullableShipmentDates) Get() *ShipmentDates {
	return v.value
}

func (v *NullableShipmentDates) Set(val *ShipmentDates) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentDates) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentDates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentDates(val *ShipmentDates) *NullableShipmentDates {
	return &NullableShipmentDates{value: val, isSet: true}
}

func (v NullableShipmentDates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentDates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


