/*
The Selling Partner API for Invoices.

Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.

API version: 2024-06-19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicesapimodel20240619

import (
	"encoding/json"
)

// checks if the InvoicesAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoicesAttributes{}

// InvoicesAttributes An object that contains the invoice attributes definition.
type InvoicesAttributes struct {
	// A list of all the options that are available for the invoice status attribute.
	InvoiceStatusOptions []AttributeOption `json:"invoiceStatusOptions,omitempty"`
	// A list of all the options that are available for the invoice type attribute.
	InvoiceTypeOptions []AttributeOption `json:"invoiceTypeOptions,omitempty"`
	// A list of all the options that are available for the transaction identifier name attribute.
	TransactionIdentifierNameOptions []AttributeOption `json:"transactionIdentifierNameOptions,omitempty"`
	// A list of all the options that are available for the transaction type attribute.
	TransactionTypeOptions []AttributeOption `json:"transactionTypeOptions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InvoicesAttributes InvoicesAttributes

// NewInvoicesAttributes instantiates a new InvoicesAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoicesAttributes() *InvoicesAttributes {
	this := InvoicesAttributes{}
	return &this
}

// NewInvoicesAttributesWithDefaults instantiates a new InvoicesAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoicesAttributesWithDefaults() *InvoicesAttributes {
	this := InvoicesAttributes{}
	return &this
}

// GetInvoiceStatusOptions returns the InvoiceStatusOptions field value if set, zero value otherwise.
func (o *InvoicesAttributes) GetInvoiceStatusOptions() []AttributeOption {
	if o == nil || IsNil(o.InvoiceStatusOptions) {
		var ret []AttributeOption
		return ret
	}
	return o.InvoiceStatusOptions
}

// GetInvoiceStatusOptionsOk returns a tuple with the InvoiceStatusOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicesAttributes) GetInvoiceStatusOptionsOk() ([]AttributeOption, bool) {
	if o == nil || IsNil(o.InvoiceStatusOptions) {
		return nil, false
	}
	return o.InvoiceStatusOptions, true
}

// HasInvoiceStatusOptions returns a boolean if a field has been set.
func (o *InvoicesAttributes) HasInvoiceStatusOptions() bool {
	if o != nil && !IsNil(o.InvoiceStatusOptions) {
		return true
	}

	return false
}

// SetInvoiceStatusOptions gets a reference to the given []AttributeOption and assigns it to the InvoiceStatusOptions field.
func (o *InvoicesAttributes) SetInvoiceStatusOptions(v []AttributeOption) {
	o.InvoiceStatusOptions = v
}

// GetInvoiceTypeOptions returns the InvoiceTypeOptions field value if set, zero value otherwise.
func (o *InvoicesAttributes) GetInvoiceTypeOptions() []AttributeOption {
	if o == nil || IsNil(o.InvoiceTypeOptions) {
		var ret []AttributeOption
		return ret
	}
	return o.InvoiceTypeOptions
}

// GetInvoiceTypeOptionsOk returns a tuple with the InvoiceTypeOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicesAttributes) GetInvoiceTypeOptionsOk() ([]AttributeOption, bool) {
	if o == nil || IsNil(o.InvoiceTypeOptions) {
		return nil, false
	}
	return o.InvoiceTypeOptions, true
}

// HasInvoiceTypeOptions returns a boolean if a field has been set.
func (o *InvoicesAttributes) HasInvoiceTypeOptions() bool {
	if o != nil && !IsNil(o.InvoiceTypeOptions) {
		return true
	}

	return false
}

// SetInvoiceTypeOptions gets a reference to the given []AttributeOption and assigns it to the InvoiceTypeOptions field.
func (o *InvoicesAttributes) SetInvoiceTypeOptions(v []AttributeOption) {
	o.InvoiceTypeOptions = v
}

// GetTransactionIdentifierNameOptions returns the TransactionIdentifierNameOptions field value if set, zero value otherwise.
func (o *InvoicesAttributes) GetTransactionIdentifierNameOptions() []AttributeOption {
	if o == nil || IsNil(o.TransactionIdentifierNameOptions) {
		var ret []AttributeOption
		return ret
	}
	return o.TransactionIdentifierNameOptions
}

// GetTransactionIdentifierNameOptionsOk returns a tuple with the TransactionIdentifierNameOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicesAttributes) GetTransactionIdentifierNameOptionsOk() ([]AttributeOption, bool) {
	if o == nil || IsNil(o.TransactionIdentifierNameOptions) {
		return nil, false
	}
	return o.TransactionIdentifierNameOptions, true
}

// HasTransactionIdentifierNameOptions returns a boolean if a field has been set.
func (o *InvoicesAttributes) HasTransactionIdentifierNameOptions() bool {
	if o != nil && !IsNil(o.TransactionIdentifierNameOptions) {
		return true
	}

	return false
}

// SetTransactionIdentifierNameOptions gets a reference to the given []AttributeOption and assigns it to the TransactionIdentifierNameOptions field.
func (o *InvoicesAttributes) SetTransactionIdentifierNameOptions(v []AttributeOption) {
	o.TransactionIdentifierNameOptions = v
}

// GetTransactionTypeOptions returns the TransactionTypeOptions field value if set, zero value otherwise.
func (o *InvoicesAttributes) GetTransactionTypeOptions() []AttributeOption {
	if o == nil || IsNil(o.TransactionTypeOptions) {
		var ret []AttributeOption
		return ret
	}
	return o.TransactionTypeOptions
}

// GetTransactionTypeOptionsOk returns a tuple with the TransactionTypeOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoicesAttributes) GetTransactionTypeOptionsOk() ([]AttributeOption, bool) {
	if o == nil || IsNil(o.TransactionTypeOptions) {
		return nil, false
	}
	return o.TransactionTypeOptions, true
}

// HasTransactionTypeOptions returns a boolean if a field has been set.
func (o *InvoicesAttributes) HasTransactionTypeOptions() bool {
	if o != nil && !IsNil(o.TransactionTypeOptions) {
		return true
	}

	return false
}

// SetTransactionTypeOptions gets a reference to the given []AttributeOption and assigns it to the TransactionTypeOptions field.
func (o *InvoicesAttributes) SetTransactionTypeOptions(v []AttributeOption) {
	o.TransactionTypeOptions = v
}

func (o InvoicesAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoicesAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InvoiceStatusOptions) {
		toSerialize["invoiceStatusOptions"] = o.InvoiceStatusOptions
	}
	if !IsNil(o.InvoiceTypeOptions) {
		toSerialize["invoiceTypeOptions"] = o.InvoiceTypeOptions
	}
	if !IsNil(o.TransactionIdentifierNameOptions) {
		toSerialize["transactionIdentifierNameOptions"] = o.TransactionIdentifierNameOptions
	}
	if !IsNil(o.TransactionTypeOptions) {
		toSerialize["transactionTypeOptions"] = o.TransactionTypeOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InvoicesAttributes) UnmarshalJSON(data []byte) (err error) {
	varInvoicesAttributes := _InvoicesAttributes{}

	err = json.Unmarshal(data, &varInvoicesAttributes)

	if err != nil {
		return err
	}

	*o = InvoicesAttributes(varInvoicesAttributes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "invoiceStatusOptions")
		delete(additionalProperties, "invoiceTypeOptions")
		delete(additionalProperties, "transactionIdentifierNameOptions")
		delete(additionalProperties, "transactionTypeOptions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInvoicesAttributes struct {
	value *InvoicesAttributes
	isSet bool
}

func (v NullableInvoicesAttributes) Get() *InvoicesAttributes {
	return v.value
}

func (v *NullableInvoicesAttributes) Set(val *InvoicesAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoicesAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoicesAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoicesAttributes(val *InvoicesAttributes) *NullableInvoicesAttributes {
	return &NullableInvoicesAttributes{value: val, isSet: true}
}

func (v NullableInvoicesAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoicesAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


