/*
The Selling Partner API for Invoices.

Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.

API version: 2024-06-19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicesapimodel20240619

import (
	"encoding/json"
)

// checks if the InvoiceError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceError{}

// InvoiceError An invoice creation error occurrence.
type InvoiceError struct {
	// A text description of the error.
	Description *string `json:"description,omitempty"`
	// The code of the error.
	ErrorCode *string `json:"errorCode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InvoiceError InvoiceError

// NewInvoiceError instantiates a new InvoiceError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceError() *InvoiceError {
	this := InvoiceError{}
	return &this
}

// NewInvoiceErrorWithDefaults instantiates a new InvoiceError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceErrorWithDefaults() *InvoiceError {
	this := InvoiceError{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InvoiceError) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceError) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InvoiceError) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InvoiceError) SetDescription(v string) {
	o.Description = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *InvoiceError) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceError) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *InvoiceError) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *InvoiceError) SetErrorCode(v string) {
	o.ErrorCode = &v
}

func (o InvoiceError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InvoiceError) UnmarshalJSON(data []byte) (err error) {
	varInvoiceError := _InvoiceError{}

	err = json.Unmarshal(data, &varInvoiceError)

	if err != nil {
		return err
	}

	*o = InvoiceError(varInvoiceError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "errorCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInvoiceError struct {
	value *InvoiceError
	isSet bool
}

func (v NullableInvoiceError) Get() *InvoiceError {
	return v.value
}

func (v *NullableInvoiceError) Set(val *InvoiceError) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceError) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceError(val *InvoiceError) *NullableInvoiceError {
	return &NullableInvoiceError{value: val, isSet: true}
}

func (v NullableInvoiceError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


