/*
Selling Partner API for Easy Ship

Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).

API version: 2022-03-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package easyship20220323

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdatePackageDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePackageDetails{}

// UpdatePackageDetails Request to update the time slot of a package.
type UpdatePackageDetails struct {
	ScheduledPackageId ScheduledPackageId `json:"scheduledPackageId"`
	PackageTimeSlot TimeSlot `json:"packageTimeSlot"`
	AdditionalProperties map[string]interface{}
}

type _UpdatePackageDetails UpdatePackageDetails

// NewUpdatePackageDetails instantiates a new UpdatePackageDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePackageDetails(scheduledPackageId ScheduledPackageId, packageTimeSlot TimeSlot) *UpdatePackageDetails {
	this := UpdatePackageDetails{}
	this.ScheduledPackageId = scheduledPackageId
	this.PackageTimeSlot = packageTimeSlot
	return &this
}

// NewUpdatePackageDetailsWithDefaults instantiates a new UpdatePackageDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePackageDetailsWithDefaults() *UpdatePackageDetails {
	this := UpdatePackageDetails{}
	return &this
}

// GetScheduledPackageId returns the ScheduledPackageId field value
func (o *UpdatePackageDetails) GetScheduledPackageId() ScheduledPackageId {
	if o == nil {
		var ret ScheduledPackageId
		return ret
	}

	return o.ScheduledPackageId
}

// GetScheduledPackageIdOk returns a tuple with the ScheduledPackageId field value
// and a boolean to check if the value has been set.
func (o *UpdatePackageDetails) GetScheduledPackageIdOk() (*ScheduledPackageId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledPackageId, true
}

// SetScheduledPackageId sets field value
func (o *UpdatePackageDetails) SetScheduledPackageId(v ScheduledPackageId) {
	o.ScheduledPackageId = v
}

// GetPackageTimeSlot returns the PackageTimeSlot field value
func (o *UpdatePackageDetails) GetPackageTimeSlot() TimeSlot {
	if o == nil {
		var ret TimeSlot
		return ret
	}

	return o.PackageTimeSlot
}

// GetPackageTimeSlotOk returns a tuple with the PackageTimeSlot field value
// and a boolean to check if the value has been set.
func (o *UpdatePackageDetails) GetPackageTimeSlotOk() (*TimeSlot, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PackageTimeSlot, true
}

// SetPackageTimeSlot sets field value
func (o *UpdatePackageDetails) SetPackageTimeSlot(v TimeSlot) {
	o.PackageTimeSlot = v
}

func (o UpdatePackageDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePackageDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scheduledPackageId"] = o.ScheduledPackageId
	toSerialize["packageTimeSlot"] = o.PackageTimeSlot

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdatePackageDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scheduledPackageId",
		"packageTimeSlot",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePackageDetails := _UpdatePackageDetails{}

	err = json.Unmarshal(data, &varUpdatePackageDetails)

	if err != nil {
		return err
	}

	*o = UpdatePackageDetails(varUpdatePackageDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "scheduledPackageId")
		delete(additionalProperties, "packageTimeSlot")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdatePackageDetails struct {
	value *UpdatePackageDetails
	isSet bool
}

func (v NullableUpdatePackageDetails) Get() *UpdatePackageDetails {
	return v.value
}

func (v *NullableUpdatePackageDetails) Set(val *UpdatePackageDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePackageDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePackageDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePackageDetails(val *UpdatePackageDetails) *NullableUpdatePackageDetails {
	return &NullableUpdatePackageDetails{value: val, isSet: true}
}

func (v NullableUpdatePackageDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePackageDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


