/*
Amazon Shipping API

The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.

API version: v2
Contact: swa-api-core@amazon.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shippingv2

import (
	"encoding/json"
)

// checks if the CollectionFormsHistoryRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionFormsHistoryRecord{}

// CollectionFormsHistoryRecord Active Account Details
type CollectionFormsHistoryRecord struct {
	// The carrier name for the offering.
	CarrierName *string `json:"carrierName,omitempty"`
	// Creation Time for this account.
	CreationDate *string `json:"creationDate,omitempty"`
	GenerationStatus *GenerationStatus `json:"generationStatus,omitempty"`
	// Collection Form Id for Reprint .
	CollectionFormId *string `json:"collectionFormId,omitempty"`
	ShipFromAddress *Address `json:"shipFromAddress,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CollectionFormsHistoryRecord CollectionFormsHistoryRecord

// NewCollectionFormsHistoryRecord instantiates a new CollectionFormsHistoryRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionFormsHistoryRecord() *CollectionFormsHistoryRecord {
	this := CollectionFormsHistoryRecord{}
	return &this
}

// NewCollectionFormsHistoryRecordWithDefaults instantiates a new CollectionFormsHistoryRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionFormsHistoryRecordWithDefaults() *CollectionFormsHistoryRecord {
	this := CollectionFormsHistoryRecord{}
	return &this
}

// GetCarrierName returns the CarrierName field value if set, zero value otherwise.
func (o *CollectionFormsHistoryRecord) GetCarrierName() string {
	if o == nil || IsNil(o.CarrierName) {
		var ret string
		return ret
	}
	return *o.CarrierName
}

// GetCarrierNameOk returns a tuple with the CarrierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionFormsHistoryRecord) GetCarrierNameOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierName) {
		return nil, false
	}
	return o.CarrierName, true
}

// HasCarrierName returns a boolean if a field has been set.
func (o *CollectionFormsHistoryRecord) HasCarrierName() bool {
	if o != nil && !IsNil(o.CarrierName) {
		return true
	}

	return false
}

// SetCarrierName gets a reference to the given string and assigns it to the CarrierName field.
func (o *CollectionFormsHistoryRecord) SetCarrierName(v string) {
	o.CarrierName = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *CollectionFormsHistoryRecord) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate) {
		var ret string
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionFormsHistoryRecord) GetCreationDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *CollectionFormsHistoryRecord) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given string and assigns it to the CreationDate field.
func (o *CollectionFormsHistoryRecord) SetCreationDate(v string) {
	o.CreationDate = &v
}

// GetGenerationStatus returns the GenerationStatus field value if set, zero value otherwise.
func (o *CollectionFormsHistoryRecord) GetGenerationStatus() GenerationStatus {
	if o == nil || IsNil(o.GenerationStatus) {
		var ret GenerationStatus
		return ret
	}
	return *o.GenerationStatus
}

// GetGenerationStatusOk returns a tuple with the GenerationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionFormsHistoryRecord) GetGenerationStatusOk() (*GenerationStatus, bool) {
	if o == nil || IsNil(o.GenerationStatus) {
		return nil, false
	}
	return o.GenerationStatus, true
}

// HasGenerationStatus returns a boolean if a field has been set.
func (o *CollectionFormsHistoryRecord) HasGenerationStatus() bool {
	if o != nil && !IsNil(o.GenerationStatus) {
		return true
	}

	return false
}

// SetGenerationStatus gets a reference to the given GenerationStatus and assigns it to the GenerationStatus field.
func (o *CollectionFormsHistoryRecord) SetGenerationStatus(v GenerationStatus) {
	o.GenerationStatus = &v
}

// GetCollectionFormId returns the CollectionFormId field value if set, zero value otherwise.
func (o *CollectionFormsHistoryRecord) GetCollectionFormId() string {
	if o == nil || IsNil(o.CollectionFormId) {
		var ret string
		return ret
	}
	return *o.CollectionFormId
}

// GetCollectionFormIdOk returns a tuple with the CollectionFormId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionFormsHistoryRecord) GetCollectionFormIdOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionFormId) {
		return nil, false
	}
	return o.CollectionFormId, true
}

// HasCollectionFormId returns a boolean if a field has been set.
func (o *CollectionFormsHistoryRecord) HasCollectionFormId() bool {
	if o != nil && !IsNil(o.CollectionFormId) {
		return true
	}

	return false
}

// SetCollectionFormId gets a reference to the given string and assigns it to the CollectionFormId field.
func (o *CollectionFormsHistoryRecord) SetCollectionFormId(v string) {
	o.CollectionFormId = &v
}

// GetShipFromAddress returns the ShipFromAddress field value if set, zero value otherwise.
func (o *CollectionFormsHistoryRecord) GetShipFromAddress() Address {
	if o == nil || IsNil(o.ShipFromAddress) {
		var ret Address
		return ret
	}
	return *o.ShipFromAddress
}

// GetShipFromAddressOk returns a tuple with the ShipFromAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionFormsHistoryRecord) GetShipFromAddressOk() (*Address, bool) {
	if o == nil || IsNil(o.ShipFromAddress) {
		return nil, false
	}
	return o.ShipFromAddress, true
}

// HasShipFromAddress returns a boolean if a field has been set.
func (o *CollectionFormsHistoryRecord) HasShipFromAddress() bool {
	if o != nil && !IsNil(o.ShipFromAddress) {
		return true
	}

	return false
}

// SetShipFromAddress gets a reference to the given Address and assigns it to the ShipFromAddress field.
func (o *CollectionFormsHistoryRecord) SetShipFromAddress(v Address) {
	o.ShipFromAddress = &v
}

func (o CollectionFormsHistoryRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionFormsHistoryRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CarrierName) {
		toSerialize["carrierName"] = o.CarrierName
	}
	if !IsNil(o.CreationDate) {
		toSerialize["creationDate"] = o.CreationDate
	}
	if !IsNil(o.GenerationStatus) {
		toSerialize["generationStatus"] = o.GenerationStatus
	}
	if !IsNil(o.CollectionFormId) {
		toSerialize["collectionFormId"] = o.CollectionFormId
	}
	if !IsNil(o.ShipFromAddress) {
		toSerialize["shipFromAddress"] = o.ShipFromAddress
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CollectionFormsHistoryRecord) UnmarshalJSON(data []byte) (err error) {
	varCollectionFormsHistoryRecord := _CollectionFormsHistoryRecord{}

	err = json.Unmarshal(data, &varCollectionFormsHistoryRecord)

	if err != nil {
		return err
	}

	*o = CollectionFormsHistoryRecord(varCollectionFormsHistoryRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "carrierName")
		delete(additionalProperties, "creationDate")
		delete(additionalProperties, "generationStatus")
		delete(additionalProperties, "collectionFormId")
		delete(additionalProperties, "shipFromAddress")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCollectionFormsHistoryRecord struct {
	value *CollectionFormsHistoryRecord
	isSet bool
}

func (v NullableCollectionFormsHistoryRecord) Get() *CollectionFormsHistoryRecord {
	return v.value
}

func (v *NullableCollectionFormsHistoryRecord) Set(val *CollectionFormsHistoryRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionFormsHistoryRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionFormsHistoryRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionFormsHistoryRecord(val *CollectionFormsHistoryRecord) *NullableCollectionFormsHistoryRecord {
	return &NullableCollectionFormsHistoryRecord{value: val, isSet: true}
}

func (v NullableCollectionFormsHistoryRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionFormsHistoryRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


