/*
Amazon Shipping API

The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.

API version: v2
Contact: swa-api-core@amazon.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package shippingv2

import (
	"encoding/json"
	"fmt"
)

// checks if the ServiceSelection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceSelection{}

// ServiceSelection Service Selection Criteria.
type ServiceSelection struct {
	// A list of ServiceId.
	ServiceId []string `json:"serviceId"`
	AdditionalProperties map[string]interface{}
}

type _ServiceSelection ServiceSelection

// NewServiceSelection instantiates a new ServiceSelection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceSelection(serviceId []string) *ServiceSelection {
	this := ServiceSelection{}
	this.ServiceId = serviceId
	return &this
}

// NewServiceSelectionWithDefaults instantiates a new ServiceSelection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceSelectionWithDefaults() *ServiceSelection {
	this := ServiceSelection{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *ServiceSelection) GetServiceId() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ServiceSelection) GetServiceIdOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceId, true
}

// SetServiceId sets field value
func (o *ServiceSelection) SetServiceId(v []string) {
	o.ServiceId = v
}

func (o ServiceSelection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceSelection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["serviceId"] = o.ServiceId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceSelection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"serviceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceSelection := _ServiceSelection{}

	err = json.Unmarshal(data, &varServiceSelection)

	if err != nil {
		return err
	}

	*o = ServiceSelection(varServiceSelection)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "serviceId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceSelection struct {
	value *ServiceSelection
	isSet bool
}

func (v NullableServiceSelection) Get() *ServiceSelection {
	return v.value
}

func (v *NullableServiceSelection) Set(val *ServiceSelection) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceSelection) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceSelection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceSelection(val *ServiceSelection) *NullableServiceSelection {
	return &NullableServiceSelection{value: val, isSet: true}
}

func (v NullableServiceSelection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceSelection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


