/*
The Selling Partner API for FBA inbound operations.

The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.

API version: 2024-03-20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fulfillmentinbound20240320

import (
	"encoding/json"
	"fmt"
)

// checks if the CancelInboundPlanResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelInboundPlanResponse{}

// CancelInboundPlanResponse The `cancelInboundPlan` response.
type CancelInboundPlanResponse struct {
	// UUID for the given operation.
	OperationId string `json:"operationId" validate:"regexp=^[a-zA-Z0-9-]*$"`
	AdditionalProperties map[string]interface{}
}

type _CancelInboundPlanResponse CancelInboundPlanResponse

// NewCancelInboundPlanResponse instantiates a new CancelInboundPlanResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelInboundPlanResponse(operationId string) *CancelInboundPlanResponse {
	this := CancelInboundPlanResponse{}
	this.OperationId = operationId
	return &this
}

// NewCancelInboundPlanResponseWithDefaults instantiates a new CancelInboundPlanResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelInboundPlanResponseWithDefaults() *CancelInboundPlanResponse {
	this := CancelInboundPlanResponse{}
	return &this
}

// GetOperationId returns the OperationId field value
func (o *CancelInboundPlanResponse) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *CancelInboundPlanResponse) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *CancelInboundPlanResponse) SetOperationId(v string) {
	o.OperationId = v
}

func (o CancelInboundPlanResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelInboundPlanResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operationId"] = o.OperationId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CancelInboundPlanResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operationId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelInboundPlanResponse := _CancelInboundPlanResponse{}

	err = json.Unmarshal(data, &varCancelInboundPlanResponse)

	if err != nil {
		return err
	}

	*o = CancelInboundPlanResponse(varCancelInboundPlanResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operationId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCancelInboundPlanResponse struct {
	value *CancelInboundPlanResponse
	isSet bool
}

func (v NullableCancelInboundPlanResponse) Get() *CancelInboundPlanResponse {
	return v.value
}

func (v *NullableCancelInboundPlanResponse) Set(val *CancelInboundPlanResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelInboundPlanResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelInboundPlanResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelInboundPlanResponse(val *CancelInboundPlanResponse) *NullableCancelInboundPlanResponse {
	return &NullableCancelInboundPlanResponse{value: val, isSet: true}
}

func (v NullableCancelInboundPlanResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelInboundPlanResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


